import React from 'react';
import "./globals.css";
// Removed bleeding effect stylesheet
import ThemeSwitcher from "@/components/ThemeSwitcher";
import UuidInitializer from "@/components/UuidInitializer";
import Script from "next/script";

const GA_MEASUREMENT_ID = 'G-LLWRNWWS0H';
const ADSENSE_CLIENT_ID = 'ca-pub-8850424858354795';
const ENABLE_ANALYTICS = process.env.NEXT_PUBLIC_ENABLE_ANALYTICS === 'true';
const ENABLE_ADS = process.env.NEXT_PUBLIC_ENABLE_ADS === 'true';

export const viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 5,
  userScalable: true,
  themeColor: '#000000',
};

export const metadata = {
  metadataBase: new URL('https://www.ifonlyisentthis.com'),
  title: "If Only I Sent This – Anonymous Unsent Messages & Memories",
  description:
    "Share unsent memories, anonymous confessions, and heartfelt messages you were never ready to send.",
  other: {
    'cache-control': 'no-cache, no-store, must-revalidate',
    'pragma': 'no-cache',
    'expires': '0',
    'apple-mobile-web-app-capable': 'yes',
    'apple-mobile-web-app-status-bar-style': 'black-translucent',
    'mobile-web-app-capable': 'yes',
    'format-detection': 'telephone=no',
  },
  keywords: [
    "unsent messages",
    "unsent letters",
    "unsent project",
    "unsent project alternative",
    "unsent project alternatives",
    "sites like the unsent project",
    "unsent project competitor",
    "unsent project reddit",
    "unsent project youtube",
    "unsent message archive",
    "the unsent project alternative",
    "the unsent project alternatives",
    "the sites like the unsent project",
    "the unsent project competitor",
    "the unsent project reddit",
    "the unsent project youtube",
    "unsent message archive",
    "anonymous confession site",
    "anonymous letter platform",
    "indie unsent project",
    "modern unsent project",
    // Celebrity + high-volume pop culture names
    "taylor swift",
    "selena gomez",
    "justin bieber",
    "ariana grande",
    "billie eilish",
    "olivia rodrigo",
    "dua lipa",
    "beyonce",
    "rihanna",
    "lady gaga",
    "drake",
    "the weeknd",
    "kendrick lamar",
    "travis scott",
    "post malone",
    "ed sheeran",
    "shawn mendes",
    "camila cabello",
    "rosalia",
    "bad bunny",
    "karol g",
    "maluma",
    "anitta",
    "shakira",
    "j balvin",
    "doja cat",
    "ice spice",
    "nicki minaj",
    "megan thee stallion",
    "sza",
    "lana del rey",
    "sabrina carpenter",
    "jungkook",
    "jimin",
    "kim taehyung",
    "blackpink",
    "jennie kim",
    "lisa manoban",
    "jisoo",
    "rose blackpink",
    "cristiano ronaldo",
    "lionel messi",
    "neymar jr",
    "kylian mbappe",
    "erling haaland",
    "virat kohli",
    "rohit sharma",
    "ms dhoni",
    "sachin tendulkar",
    "serena williams",
    "naomi osaka",
    "novak djokovic",
    "roger federer",
    "rafael nadal",
    "lebron james",
    "stephen curry",
    "kevin durant",
    "nikola jokic",
    "giannis antetokounmpo",
    "lewis hamilton",
    "max verstappen",
    "charles leclerc",
    "lando norris",
    "timothee chalamet",
    "zendaya",
    "tom holland",
    "andrew garfield",
    "tobey maguire",
    "robert downey jr",
    "chris evans",
    "scarlett johansson",
    "florence pugh",
    "ryan gosling",
    "ryan reynolds",
    "hugh jackman",
    "margot robbie",
    "emma stone",
    "emma watson",
    "daniel radcliffe",
    "benedict cumberbatch",
    "cillian murphy",
    // High-intent trending topics
    "grammy awards",
    "coachella lineup",
    "met gala looks",
    "viral tiktok songs",
    "instagram reels trends",
    "youtube shorts ideas",
    "reddit trending communities",
    "spotify wrapped",
    "apple music replay",
    "chatgpt prompts",
    "midjourney art",
    "stable diffusion",
    "openai news",
    "google gemini",
    "crypto news today",
    "bitcoin price today",
    "ethereum price live",
    "solana price prediction",
    "nft marketplace",
    "fifa world cup 2026",
    "uefa euro 2024",
    "copa america 2024",
    "icc cricket world cup",
    "nba finals",
    "super bowl halftime show",
    "champions league final",
    "icc t20 world cup",
    "olympics 2024",
    "commonwealth games",
    "wimbledon finals",
    "tour de france",
    "formula 1 schedule",
    "metaverse news",
    "elon musk",
    "jeff bezos",
    "mark zuckerberg",
    "bill gates",
    "warren buffett",
    "sundar pichai",
    "satya nadella",
    "tim cook",
    "nvidia earnings",
    "tesla stock news",
    "apple stock news",
    "tcs stock price",
    "reliance share price",
    "tata ipo",
    "india stock market",
    "sensex today",
    "nifty today",
    "ai startup ideas",
    "passive income online",
    "side hustle ideas",
    "best breakup songs",
    "healing playlist",
    "sad song lyrics",
    "heartbreak poems",
    "anonymous stories",
    "confession reddit",
    "confession tiktok",
    "viral heartbreak trend",
    "relationship advice reddit",
    "tiktok breakup trend",
    "youtube breakup vlog",
    "spotify heartbreak playlist",
    "apple music sad songs",
    "soundcloud breakup tracks",
    "latest bollywood songs",
    "bollywood breakup songs",
    "tollywood breakup songs",
    "kollywood sad songs",
    "kdrama heartbreak scenes",
    "kpop breakup songs",
    "anime heartbreak quotes",
    "manga romance drama",
    "netflix heartbreak movies",
    "hulu romance shows",
    "prime video drama series",
    "disney plus breakup movies",
    "paramount plus teen drama",
    "hbo heartbreak shows",
    "succession quotes",
    "the bear quotes",
    "euphoria heartbreak",
    "outer banks love triangle",
    "bridgerton romance",
    "love is blind drama",
    "too hot to handle fights",
    "perfect match netflix",
    "fboy island confessions",
    "the bachelor breakup",
    "the bachelorette heartbreak",
    "love island casa amor",
    "90 day fiance breakup",
    "indian matchmaking drama",
    "married at first sight fight",
    "gossip girl quotes",
    "one tree hill heartbreak",
    "the vampire diaries breakup",
    "grey's anatomy sad episode",
    "this is us heartbreak",
    "the notebook quotes",
    "la la land ending",
    "perks of being a wallflower quote",
    "john green quotes",
    "colleen hoover books",
    "emily henry books",
    "romantic poetry lines",
    "urdu shayari heartbreak",
    "hindi shayari breakup",
    "punjabi sad songs",
    "tamil sad songs",
    "telugu sad songs",
    "malayalam sad songs",
    "kannada sad songs",
    "marathi breakup songs",
    "gujarati love songs",
    "bengali heartbreak songs",
    "desi breakup playlist",
    "indie heartbreak playlist",
    "acoustic sad songs",
    "lofi breakup mix",
    "lofi study playlist",
    "rainy day playlists",
    "midnight thoughts quotes",
    "late night text ideas",
    "unsent love letter template",
    "confession letter format",
    "how to apologize to ex",
    "should i text my ex",
    "no contact rule day 30",
    "moving on tips reddit",
    "healing after breakup",
    "self care after breakup",
    "journaling prompts heartbreak",
    // Grief, breakup, and cathartic search intent
    "grief support",
    "mourning quotes",
    "loss of parent",
    "loss of mother",
    "loss of father",
    "loss of sibling",
    "loss of friend",
    "loss of grandparent",
    "coping with grief",
    "how to write eulogy",
    "memorial letter ideas",
    "anniversary grief",
    "grief journal prompts",
    "bereavement support",
    "grief hotlines",
    "therapy for grief",
    "how to move on after death",
    "grief music playlist",
    "songs for funerals",
    "sad instrumental music",
    "piano sad songs",
    "violin sad songs",
    "rain sounds heartbreak",
    "sleep meditation grief",
    "guided meditation heartbreak",
    "late night depression thoughts",
    "sad poem generator",
    "unsent goodbye letter",
    "goodbye letter to ex",
    "goodbye letter to deceased",
    "how to say goodbye forever",
    "closure letter template",
    "writing to ex for closure",
    "should i send closure text",
    "what to text ex after months",
    "ex moved on what to do",
    "ex engaged feelings",
    "ex getting married",
    "how to stop missing ex",
    "when will i stop loving ex",
    "missing you quotes",
    "heartbreak diary ideas",
    "midnight diary prompts",
    "what to do when lonely",
    "lonely on weekends",
    "lonely at college",
    "lonely in marriage",
    "emotionally unavailable partner",
    "toxic relationship signs",
    "getting over narcissist",
    "healing from narcissistic abuse",
    "attachment style quiz",
    "fearful avoidant healing",
    "anxious attachment breakup",
    "dismissive avoidant breakup",
    "ghosted what to do",
    "breadcrumbing relationship",
    "situation ship tips",
    "friends with benefits feelings",
    "backslide with ex",
    "rebounds after breakup",
    "dating after breakup",
    "dating yourself challenge",
    "solo date ideas",
    "self love rituals",
    "mirror affirmations",
    "daily affirmations heartbreak",
    "affirmations for grief",
    "manifesting closure",
    "manifesting text from ex",
    "manifesting apology",
    "angel numbers heartbreak",
    "222 meaning breakup",
    "444 meaning grief",
    "ending situationship",
    "blocking ex pros cons",
    "unblocking ex meaning",
    "why did ex unblock me",
    "watching ex stories",
    "ex watching my story",
    "mutual friends with ex",
    "returning ex stories",
    "should i meet ex for closure",
    "writing letters never sent",
    "unsent therapy exercise",
    "unsent message trend",
    "anonymous venting sites",
    "confession hotline",
    "sad reddit communities",
    "true off my chest",
    "confession subreddits",
    "breakup subreddits",
    "venting tik tok",
    "venting instagram",
    "heartbreak pinterest quotes",
    "sad aesthetic wallpapers",
    "digital scrapbook grief",
    "memory capsule ideas",
    "time capsule letter",
    "message to future self",
    "message to younger self",
    "journaling apps breakup",
    "therapy alternatives online",
    "online grief circles",
    "anonymous therapy chat",
    "text therapy services",
    // Popular culture & trending
    "justin bieber breakup songs",
    "justin bieber heartbreak",
    "heather conan gray",
    "heather song meaning",
    "drivers license olivia rodrigo",
    "olivia rodrigo breakup songs",
    "taylor swift heartbreak songs",
    "taylor swift breakup playlist",
    "all too well taylor swift",
    "someone like you adele",
    "someone you loved lewis capaldi",
    "when the party's over billie eilish",
    "billie eilish sad songs",
    "ariana grande thank u next",
    "thank u next breakup anthem",
    "happier than ever billie eilish",
    "good 4 u olivia rodrigo",
    "traitor olivia rodrigo",
    "deja vu olivia rodrigo",
    "cardigan taylor swift",
    "exile taylor swift",
    "the 1 taylor swift",
    "champagne problems taylor swift",
    "right where you left me",
    // Christmas & December Breakup Keywords (Trending Now!)
    "christmas breakup songs",
    "christmas breakup",
    "christmas alone after breakup",
    "breakup on christmas",
    "breakup before christmas",
    "christmas without you",
    "spending christmas alone",
    "first christmas after breakup",
    "christmas heartbreak",
    "christmas sad songs",
    "december breakup",
    "december heartbreak",
    "breakup in december",
    "december sad songs",
    "breakup during holidays",
    "holiday breakup songs",
    "holiday heartbreak",
    "breakup on christmas eve",
    "christmas eve alone",
    "christmas day breakup",
    "new years breakup",
    "new years eve breakup",
    "new years alone",
    "breakup before new year",
    "last christmas wham",
    "last christmas breakup song",
    "last christmas lyrics",
    "last christmas meaning",
    "last christmas heartbreak",
    "last christmas alone",
    "last christmas without you",
    "all i want for christmas is you breakup",
    "mariah carey christmas breakup",
    "mistletoe justin bieber breakup",
    "santa tell me ariana grande",
    "christmas tree v heartbreak",
    "winter things ariana grande",
    "snow patrol christmas songs",
    "coldplay christmas lights",
    "the 1975 christmas song",
    "halsey christmas song",
    "christmas songs about heartbreak",
    "christmas songs about breakup",
    "christmas songs about missing someone",
    "christmas songs about being alone",
    "sad christmas songs",
    "depressing christmas songs",
    "christmas songs for breakup",
    "christmas playlist breakup",
    "christmas alone playlist",
    "anti christmas songs",
    "christmas blues songs",
    "lonely christmas songs",
    "missing you at christmas",
    "thinking of you at christmas",
    "wish you were here christmas",
    "empty chair at christmas",
    "christmas memories sad",
    "christmas nostalgia heartbreak",
    "christmas 2024 breakup",
    "december 2024 breakup",
    "christmas gift for ex",
    "christmas text to ex",
    "christmas message to ex",
    "should i text my ex on christmas",
    "ex texted me on christmas",
    "seeing ex at christmas",
    "family christmas after breakup",
    "awkward christmas after breakup",
    "heather conan gray christmas",
    "heather song christmas vibes",
    "drivers license christmas",
    "all too well christmas",
    "champagne problems christmas",
    "coney island christmas",
    "evermore christmas",
    "folklore christmas",
    "winter breakup songs",
    "winter heartbreak songs",
    "winter sad songs",
    "valentine's day breakup",
    "valentine heartbreak",
    "valentine's day alone",
    "holiday breakup",
    "summer breakup songs",
    "spring breakup songs",
    "fall breakup songs",
    "midnight rain taylor swift",
    "anti hero taylor swift",
    "bejeweled taylor swift",
    "mastermind taylor swift",
    "question taylor swift",
    "lavender haze taylor swift",
    "snow on the beach taylor swift",
    "maroon taylor swift",
    "you're losing me taylor swift",
    "would've could've should've taylor swift",
    "bigger than the whole sky taylor swift",
    "dear john taylor swift",
    "all too well 10 minute version",
    "red taylor swift",
    "speak now taylor swift",
    "folklore taylor swift",
    "evermore taylor swift",
    "midnights taylor swift",
    "1989 taylor swift",
    "reputation taylor swift",
    "lover taylor swift",
    "fearless taylor swift",
    "enchanted taylor swift",
    "back to december taylor swift",
    "the story of us taylor swift",
    "forever and always taylor swift",
    "white horse taylor swift",
    "last kiss taylor swift",
    "sad beautiful tragic taylor swift",
    "the moment i knew taylor swift",
    "come back be here taylor swift",
    "i almost do taylor swift",
    "breathe taylor swift",
    "you're not sorry taylor swift",
    "death by a thousand cuts taylor swift",
    "cruel summer taylor swift",
    "cornelia street taylor swift",
    "the archer taylor swift",
    "false god taylor swift",
    "afterglow taylor swift",
    "daylight taylor swift",
    "it's time to go taylor swift",
    "closure taylor swift",
    "happiness taylor swift",
    "coney island taylor swift",
    "tolerate it taylor swift",
    "ivy taylor swift",
    "gold rush taylor swift",
    "willow taylor swift",
    "heather unsent messages",
    "heather breakup",
    "wish you were sober conan gray",
    "maniac conan gray",
    "the cut that always bleeds conan gray",
    "astronomy conan gray",
    "people watching conan gray",
    "jigsaw conan gray",
    "comfort crowd conan gray",
    "memories conan gray",
    "fake conan gray",
    "idle town conan gray",
    "lookalike conan gray",
    "crush culture conan gray",
    "checkmate conan gray",
    "the story conan gray",
    "fight or flight conan gray",
    "overdrive conan gray",
    "telepath conan gray",
    "family line conan gray",
    "yours conan gray",
    "disaster conan gray",
    "best friend conan gray",
    "driver's license unsent",
    "drivers license breakup",
    "traitor olivia rodrigo unsent",
    "deja vu olivia rodrigo unsent",
    "favorite crime olivia rodrigo",
    "jealousy jealousy olivia rodrigo",
    "brutal olivia rodrigo",
    "happier olivia rodrigo",
    "enough for you olivia rodrigo",
    "1 step forward 3 steps back",
    "hope ur ok olivia rodrigo",
    "vampire olivia rodrigo",
    "bad idea right olivia rodrigo",
    "ballad of a homeschooled girl",
    "making the bed olivia rodrigo",
    "logical olivia rodrigo",
    "get him back olivia rodrigo",
    "love is embarrassing olivia rodrigo",
    "the grudge olivia rodrigo",
    "pretty isn't pretty olivia rodrigo",
    "teenage dream olivia rodrigo",
    "lacy olivia rodrigo",
    "so american olivia rodrig",
    "obsessed olivia rodrigo",
    "girl i've always been olivia rodrigo",
    "can't catch me now olivia rodrigo",
    "scared of my guitar olivia rodrigo",
    "stranger olivia rodrigo",
    "prison for life olivia rodrigo",
    "stranger things breakup",
    "euphoria breakup quotes",
    "13 reasons why breakup",
    "gossip girl breakup",
    "the summer i turned pretty breakup",
    "heartstopper breakup",
    "young royals breakup",
    "never have i ever breakup",
    "outer banks breakup",
    "ginny and georgia breakup",
    "you breakup scenes",
    "bridgerton heartbreak",
    "the notebook breakup",
    "titanic love story",
    "romeo and juliet tragic love",
    "500 days of summer breakup",
    "eternal sunshine of spotless mind",
    "la la land ending",
    "blue valentine breakup",
    "marriage story breakup",
    "before trilogy breakup",
    "her movie breakup",
    "lost in translation ending",
    // The Unsent Project & Similar Sites
    "the unsent project",
    "unsent project website",
    "theunsentproject.com",
    "unsent project alternative",
    "sites like the unsent project",
    "unsent project app",
    "unsent project messages",
    "unsent project browse",
    "unsent project submit",
    "unsent project archive",
    "unsent project love",
    "unsent project heartbreak",
    "unsent project read",
    "unsent project stories",
    "unsent project confessions",
    "unsent project anonymous",
    // More trending songs & artists
    "sweater weather the neighbourhood",
    "sweater weather lyrics",
    "sweater weather meaning",
    "the neighbourhood songs",
    "daddy issues the neighbourhood",
    "afraid the neighbourhood",
    "flawless the neighbourhood",
    "cry baby the neighbourhood",
    "reflections the neighbourhood",
    "alleyways the neighbourhood",
    "float the neighbourhood",
    "staying up the neighbourhood",
    "void the neighbourhood",
    "cherry flavoured the neighbourhood",
    // Sports & Celebrity heartbreak
    "cristiano ronaldo breakup",
    "ronaldo heartbreak",
    "messi breakup",
    "neymar heartbreak",
    "football player breakup",
    "celebrity breakup 2024",
    "celebrity heartbreak stories",
    "famous breakup songs",
    "celebrity breakup quotes",
    // More breakup anthems
    "someone new hozier",
    "cherry wine hozier",
    "work song hozier",
    "like real people do hozier",
    "too sweet hozier",
    "francesca hozier",
    "talk hozier",
    "from eden hozier",
    "sedated hozier",
    "shrike hozier",
    "movement hozier",
    "nobody hozier",
    "dinner and diatribes hozier",
    "de selby part 2 hozier",
    "who we are hozier",
    "unknown nth hozier",
    "i carrion hozier",
    "butchered tongue hozier",
    "anything but hozier",
    "abstract hozier",
    "all things end hozier",
    "why would you be loved hozier",
    "son of nyx hozier",
    "first light hozier",
    "damage gets done hozier",
    "wildflower and barley hozier",
    "empire now hozier",
    "fare well hozier",
    "abstract psychopomp hozier",
    "unsent love letters",
    "unsent text messages",
    "unsent emails",
    "unsent confessions",
    "unsent feelings",
    "unsent thoughts",
    "unsent memories",
    "unsent words",
    "unsent love",
    "unsent apologies",
    "unsent goodbyes",
    "unsent thank you",
    "unsent i love you",
    "unsent break up",
    "unsent heartbreak",
    "unsent first love",
    "unsent friendship",
    "unsent family",
    "unsent parents",
    "unsent ex",
    "unsent crush",
    "unsent soulmate",
    "unsent closure",
    "unsent forgiveness",
    "unsent regret",
    "unsent hope",
    "unsent dreams",
    "unsent promises",
    "unsent secrets",
    "unsent truth",
    "unsent feelings",
    "unsent emotions",
    "unsent heart",
    "unsent soul",
    "unsent mind",
    "unsent voice",
    "unsent story",
    "anonymous messages",
    "anonymous confessions",
    "anonymous letters",
    "anonymous love",
    "anonymous feelings",
    "anonymous thoughts",
    "anonymous memories",
    "anonymous heart",
    "anonymous soul",
    "anonymous voice",
    "unsent text to ex",
    "unsent message to ex",
    "unsent text to crush",
    "unsent message to crush",
    "unsent text to first love",
    "unsent message to first love",
    "unsent text to parents",
    "unsent message to parents",
    "unsent text to friend",
    "unsent message to friend",
    "unsent text to family",
    "unsent message to family",
    "unsent text to someone",
    "unsent message to someone",
    "unsent text to you",
    "unsent message to you",
    "unsent text to them",
    "unsent message to them",
    "unsent text to her",
    "unsent message to her",
    "unsent text to him",
    "unsent message to him",
    "unsent text to mom",
    "unsent message to mom",
    "unsent text to dad",
    "unsent message to dad",
    "unsent text to brother",
    "unsent message to brother",
    "unsent text to sister",
    "unsent message to sister",
    "unsent text to best friend",
    "unsent message to best friend",
    "unsent text to lover",
    "unsent message to lover",
    "unsent text to partner",
    "unsent message to partner",
    "unsent text to spouse",
    "unsent message to spouse",
    "unsent text to wife",
    "unsent message to wife",
    "unsent text to husband",
    "unsent message to husband",
    "unsent text to boyfriend",
    "unsent message to boyfriend",
    "unsent text to girlfriend",
    "unsent message to girlfriend",
    "unsent text to soulmate",
    "unsent message to soulmate",
    "unsent text to the one",
    "unsent message to the one",
    "unsent text to my love",
    "unsent message to my love",
    "unsent text to my heart",
    "unsent message to my heart",
    "unsent text to my soul",
    "unsent message to my soul",
    "unsent text to my mind",
    "unsent message to my mind",
    "unsent text to my life",
    "unsent message to my life",
    "unsent text to my world",
    "unsent message to my world",
    "unsent text to my everything",
    "unsent message to my everything",
    "unsent text to my future",
    "unsent message to my future",
    "unsent text to my past",
    "unsent message to my past",
    "unsent text to my present",
    "unsent message to my present",
    "unsent text to my dreams",
    "unsent message to my dreams",
    "unsent text to my hopes",
    "unsent message to my hopes",
    "unsent text to my fears",
    "unsent message to my fears",
    "unsent text to my regrets",
    "unsent message to my regrets",
    "unsent text to my mistakes",
    "unsent message to my mistakes",
    "unsent text to my apologies",
    "unsent message to my apologies",
    "unsent text to my forgiveness",
    "unsent message to my forgiveness",
    "unsent text to my closure",
    "unsent message to my closure",
    "unsent text to my goodbye",
    "unsent message to my goodbye",
    "unsent text to my hello",
    "unsent message to my hello",
    "unsent text to my future self",
    "unsent message to my future self",
    "unsent text to my past self",
    "unsent message to my past self",
    "unsent text to my present self",
    "unsent text to first love",
    "unsent message to first love",
    "unsent text to first crush",
    "unsent message to first crush",
    "unsent text to first kiss",
    "unsent message to first kiss",
    "unsent text to first date",
    "unsent message to first date",
    "unsent text to first relationship",
    "unsent message to first relationship",
    "unsent text to first heartbreak",
    "unsent message to first heartbreak",
    "unsent text to first breakup",
    "unsent message to first breakup",
    "unsent text to first love letter",
    "unsent message to first love letter",
    "unsent text to first love story",
    "unsent message to first love story",
    "unsent text to first love memory",
    "unsent message to first love memory",
    "unsent text to first love moment",
    "unsent message to first love moment",
    "unsent text to first love experience",
    "unsent message to first love experience",
    "unsent text to first love feelings",
    "unsent message to first love feelings",
    "unsent text to first love emotions",
    "unsent message to first love emotions",
    "unsent text to first love thoughts",
    "unsent message to first love thoughts",
    "unsent text to first love dreams",
    "unsent message to first love dreams",
    "unsent text to first love hopes",
    "unsent message to first love hopes",
    "unsent text to first love fears",
    "unsent message to first love fears",
    "unsent text to first love regrets",
    "unsent message to first love regrets",
    "unsent text to first love mistakes",
    "unsent message to first love mistakes",
    "unsent text to first love apologies",
    "unsent message to first love apologies",
    "unsent text to first love forgiveness",
    "unsent message to first love forgiveness",
    "unsent text to first love closure",
    "unsent message to first love closure",
    "unsent text to first love goodbye",
    "unsent message to first love goodbye",
    "unsent text to first love hello",
    "unsent message to first love hello",
    "unsent text to first love future",
    "unsent message to first love future",
    "unsent text to first love past",
    "unsent message to first love past",
    "unsent text to first love present",
    "unsent message to first love present",
    "breakup messages",
    "breakup texts",
    "breakup letters",
    "breakup confessions",
    "breakup feelings",
    "breakup thoughts",
    "breakup memories",
    "breakup words",
    "breakup love",
    "breakup apologies",
    "breakup goodbyes",
    "breakup thank you",
    "breakup i love you",
    "breakup heartbreak",
    "breakup first love",
    "breakup friendship",
    "breakup family",
    "breakup parents",
    "breakup ex",
    "breakup crush",
    "breakup soulmate",
    "breakup closure",
    "breakup forgiveness",
    "breakup regret",
    "breakup hope",
    "breakup dreams",
    "breakup promises",
    "breakup secrets",
    "breakup truth",
    "breakup feelings",
    "breakup emotions",
    "breakup heart",
    "breakup soul",
    "breakup mind",
    "breakup voice",
    "breakup story",
    "ex messages",
    "ex texts",
    "ex letters",
    "ex confessions",
    "ex feelings",
    "ex thoughts",
    "ex memories",
    "ex words",
    "ex love",
    "ex apologies",
    "ex goodbyes",
    "ex thank you",
    "ex i love you",
    "ex heartbreak",
    "ex first love",
    "ex friendship",
    "ex family",
    "ex parents",
    "ex crush",
    "ex soulmate",
    "ex closure",
    "ex forgiveness",
    "ex regret",
    "ex hope",
    "ex dreams",
    "ex promises",
    "ex secrets",
    "ex truth",
    "ex feelings",
    "ex emotions",
    "ex heart",
    "ex soul",
    "ex mind",
    "ex voice",
    "ex story",
    "first love messages",
    "first love texts",
    "first love letters",
    "first love confessions",
    "first love feelings",
    "first love thoughts",
    "first love memories",
    "first love words",
    "first love apologies",
    "first love goodbyes",
    "first love thank you",
    "first love i love you",
    "first love heartbreak",
    "first love friendship",
    "first love family",
    "first love parents",
    "first love ex",
    "first love crush",
    "first love soulmate",
    "first love closure",
    "first love forgiveness",
    "first love regret",
    "first love hope",
    "first love dreams",
    "first love promises",
    "first love secrets",
    "first love truth",
    "first love feelings",
    "first love emotions",
    "first love heart",
    "first love soul",
    "first love mind",
    "first love voice",
    "first love story",
    "first love memory",
    "first love moment",
    "first love experience",
    "first love journey",
    "first love beginning",
    "first love end",
    "first love start",
    "first love finish",
    "first love chapter",
    "first love page",
    "first love book",
    "first love story",
    "first love tale",
    "first love narrative",
    "first love chronicle",
    "first love history",
    "first love past",
    "first love present",
    "first love future",
    "first love yesterday",
    "first love today",
    "first love tomorrow",
    "first love forever",
    "first love always",
    "first love never",
    "first love once",
    "first love again",
    "first love more",
    "first love less",
    "first love better",
    "first love worse",
    "first love best",
    "first love worst",
    "first love perfect",
    "first love imperfect",
    "first love real",
    "first love unreal",
    "first love true",
    "first love false",
    "first love right",
    "first love wrong",
    "first love good",
    "first love bad",
    "first love happy",
    "first love sad",
    "first love joy",
    "first love pain",
    "first love smile",
    "first love tears",
    "first love laugh",
    "first love cry",
    "first love sing",
    "first love dance",
    "first love play",
    "first love work",
    "first love live",
    "first love die",
    "first love breathe",
    "first love sleep",
    "first love wake",
    "first love dream",
    "first love hope",
    "first love fear",
    "first love trust",
    "first love doubt",
    "first love believe",
    "first love know",
    "first love think",
    "first love feel",
    "first love see",
    "first love hear",
    "first love touch",
    "first love taste",
    "first love smell",
    "first love sense",
    "first love understand",
    "first love learn",
    "first love grow",
    "first love change",
    "first love become",
    "first love be",
    "never sent messages",
    "never sent texts",
    "never sent letters",
    "never sent confessions",
    "never sent feelings",
    "never sent thoughts",
    "never sent memories",
    "never sent words",
    "never sent love",
    "never sent apologies",
    "never sent goodbyes",
    "never sent thank you",
    "never sent i love you",
    "never sent heartbreak",
    "never sent first love",
    "never sent friendship",
    "never sent family",
    "never sent parents",
    "never sent ex",
    "never sent crush",
    "never sent soulmate",
    "never sent closure",
    "never sent forgiveness",
    "never sent regret",
    "never sent hope",
    "never sent dreams",
    "never sent promises",
    "never sent secrets",
    "never sent truth",
    "never sent feelings",
    "never sent emotions",
    "never sent heart",
    "never sent soul",
    "never sent mind",
    "never sent voice",
    "never sent story",
    "could not send messages",
    "could not send texts",
    "could not send letters",
    "could not send confessions",
    "could not send feelings",
    "could not send thoughts",
    "could not send memories",
    "could not send words",
    "could not send love",
    "could not send apologies",
    "could not send goodbyes",
    "could not send thank you",
    "could not send i love you",
    "could not send heartbreak",
    "could not send first love",
    "could not send friendship",
    "could not send family",
    "could not send parents",
    "could not send ex",
    "could not send crush",
    "could not send soulmate",
    "could not send closure",
    "could not send forgiveness",
    "could not send regret",
    "could not send hope",
    "could not send dreams",
    "could not send promises",
    "could not send secrets",
    "could not send truth",
    "could not send feelings",
    "could not send emotions",
    "could not send heart",
    "could not send soul",
    "could not send mind",
    "could not send voice",
    "could not send story",
    "wish i sent messages",
    "wish i sent texts",
    "wish i sent letters",
    "wish i sent confessions",
    "wish i sent feelings",
    "wish i sent thoughts",
    "wish i sent memories",
    "wish i sent words",
    "wish i sent love",
    "wish i sent apologies",
    "wish i sent goodbyes",
    "wish i sent thank you",
    "wish i sent i love you",
    "wish i sent heartbreak",
    "wish i sent first love",
    "wish i sent friendship",
    "wish i sent family",
    "wish i sent parents",
    "wish i sent ex",
    "wish i sent crush",
    "wish i sent soulmate",
    "wish i sent closure",
    "wish i sent forgiveness",
    "wish i sent regret",
    "wish i sent hope",
    "wish i sent dreams",
    "wish i sent promises",
    "wish i sent secrets",
    "wish i sent truth",
    "wish i sent feelings",
    "wish i sent emotions",
    "wish i sent heart",
    "wish i sent soul",
    "wish i sent mind",
    "wish i sent voice",
    "wish i sent story",
    "should have sent messages",
    "should have sent texts",
    "should have sent letters",
    "should have sent confessions",
    "should have sent feelings",
    "should have sent thoughts",
    "should have sent memories",
    "should have sent words",
    "should have sent love",
    "should have sent apologies",
    "should have sent goodbyes",
    "should have sent thank you",
    "should have sent i love you",
    "should have sent heartbreak",
    "should have sent first love",
    "should have sent friendship",
    "should have sent family",
    "should have sent parents",
    "should have sent ex",
    "should have sent crush",
    "should have sent soulmate",
    "should have sent closure",
    "should have sent forgiveness",
    "should have sent regret",
    "should have sent hope",
    "should have sent dreams",
    "should have sent promises",
    "should have sent secrets",
    "should have sent truth",
    "should have sent feelings",
    "should have sent emotions",
    "should have sent heart",
    "should have sent soul",
    "should have sent mind",
    "should have sent voice",
    "should have sent story",
    "if only i sent messages",
    "if only i sent texts",
    "if only i sent letters",
    "if only i sent confessions",
    "if only i sent feelings",
    "if only i sent thoughts",
    "if only i sent memories",
    "if only i sent words",
    "if only i sent love",
    "if only i sent apologies",
    "if only i sent goodbyes",
    "if only i sent thank you",
    "if only i sent i love you",
    "if only i sent heartbreak",
    "if only i sent first love",
    "if only i sent friendship",
    "if only i sent family",
    "if only i sent parents",
    "if only i sent ex",
    "if only i sent crush",
    "if only i sent soulmate",
    "if only i sent closure",
    "if only i sent forgiveness",
    "if only i sent regret",
    "if only i sent hope",
    "if only i sent dreams",
    "if only i sent promises",
    "if only i sent secrets",
    "if only i sent truth",
    "if only i sent feelings",
    "if only i sent emotions",
    "if only i sent heart",
    "if only i sent soul",
    "if only i sent mind",
    "if only i sent voice",
    "if only i sent story"
  ].join(", "),
  icons: {
    icon: [
      { url: '/favicon.ico', sizes: 'any' },
      { url: '/favicon-16x16.png', sizes: '16x16', type: 'image/png' },
      { url: '/favicon-32x32.png', sizes: '32x32', type: 'image/png' },
    ],
    apple: '/apple-touch-icon.png',
    other: [
      {
        rel: 'android-chrome-192x192',
        url: '/android-chrome-192x192.png',
      },
      {
        rel: 'android-chrome-512x512',
        url: '/android-chrome-512x512.png',
      },
    ],
  },
  manifest: '/site.webmanifest',
  openGraph: {
    title: "If Only I Sent This – Anonymous Unsent Messages & Memories",
    description:
      "Share unsent memories, anonymous confessions, and heartfelt messages you were never ready to send.",
    images: [
      {
        url: '/opengraph-image.png',
        width: 1200,
        height: 630,
        alt: 'If Only I Sent This',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: "If Only I Sent This – Anonymous Unsent Messages & Memories",
    description:
      "Share unsent memories, anonymous confessions, and heartfelt messages you were never ready to send.",
    images: ['/opengraph-image.png'],
  },
  alternates: {
    canonical: '/',
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="apple-touch-icon" href="/apple-touch-icon.png" sizes="180x180" />
        <meta name="msapplication-TileColor" content="#ffffff" />
        <meta name="msapplication-TileImage" content="/mstile-150x150.png" />
        <meta name="google-site-verification" content="-3cysNzrb6ZgU44DFdsfeiwU61zydgZWRMyXebgmsUM" />
        <meta name="robots" content="index, follow" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="color-scheme" content="light dark" />
        <meta name="referrer" content="no-referrer-when-downgrade" />
        <link rel="alternate" hrefLang="en" href="https://www.ifonlyisentthis.com/" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link rel="preconnect" href="https://www.googletagmanager.com" />
        <link rel="preconnect" href="https://www.google-analytics.com" />
        <link rel="preconnect" href="https://pagead2.googlesyndication.com" crossOrigin="anonymous" />
        <link rel="preconnect" href="https://googleads.g.doubleclick.net" crossOrigin="anonymous" />
        <link rel="preconnect" href="https://ppkbuhaklzbgwvaaoudn.supabase.co" crossOrigin="anonymous" />
        <link rel="preconnect" href="https://goltnprxtenbrkxcvsha.supabase.co" crossOrigin="anonymous" />
        <meta name="description" content="A modern archive for unsent memories and heartfelt messages. Share your unspoken thoughts and feelings in a safe, anonymous space." />
        {ENABLE_ANALYTICS && (
          <>
            <Script src={`https://www.googletagmanager.com/gtag/js?id=${GA_MEASUREMENT_ID}`} strategy="afterInteractive" />
            <Script id="gtag-init" strategy="afterInteractive">
              {`
                window.dataLayer = window.dataLayer || [];
                function gtag(){dataLayer.push(arguments);}
                gtag('js', new Date());
                gtag('config', '${GA_MEASUREMENT_ID}');
              `}
            </Script>
          </>
        )}
        <Script
          id="ld-json-org"
          type="application/ld+json"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "Organization",
              "url": "https://www.ifonlyisentthis.com",
              "logo": "https://www.ifonlyisentthis.com/favicon.ico",
              "name": "If Only I Sent This",
              "description": "A modern archive for unsent memories and heartfelt messages."
            })
          }}
        />
        
        <link rel="manifest" href="/site.webmanifest" />
        {ENABLE_ADS && (
          <Script
            src={`https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=${ADSENSE_CLIENT_ID}`}
            strategy="lazyOnload"
            crossOrigin="anonymous"
          />
        )}
      </head>
      <body className="min-h-screen bg-[var(--background)] text-[var(--text)]">
        <ThemeSwitcher />
        <UuidInitializer />
        {children}
        <Script id="ioist-startup-cleanup" strategy="afterInteractive">
          {`
            (function() {
              // Run only in production on this domain (covers subdomains)
              var host = window.location.hostname || '';
              var isProd = host === 'ifonlyisentthis.com' || host.endsWith('.ifonlyisentthis.com');
              if (!isProd) { return; }

              // Ensure we don't loop reloads: mark one-time cleanup per session
              if (sessionStorage.getItem('ioist_cleanup_done') === '1') { return; }
              sessionStorage.setItem('ioist_cleanup_done', '1');

              var cleanup = async function() {
                try {
                  // 1) Clear CacheStorage
                  if (window.caches && caches.keys) {
                    var keys = await caches.keys();
                    await Promise.all(keys.map(function(k){ return caches.delete(k); }));
                  }
                } catch(e) {}

                try {
                  // 2) Unregister any service workers for this origin
                  if (navigator.serviceWorker && navigator.serviceWorker.getRegistrations) {
                    var regs = await navigator.serviceWorker.getRegistrations();
                    await Promise.all(regs.map(function(r){ return r.unregister(); }));
                  }
                } catch(e) {}

                try {
                  // 3) Clear storage (localStorage, sessionStorage, IndexedDB)
                  localStorage.clear();
                } catch(e) {}

                try {
                  // Preserve the marker while clearing sessionStorage
                  var marker = sessionStorage.getItem('ioist_cleanup_done');
                  sessionStorage.clear();
                  sessionStorage.setItem('ioist_cleanup_done', marker || '1');
                } catch(e) {}

                try {
                  if (window.indexedDB && indexedDB.databases) {
                    var dbs = await indexedDB.databases();
                    await Promise.all((dbs || []).map(function(db){
                      if (db && db.name) { return new Promise(function(res){ var del = indexedDB.deleteDatabase(db.name); del.onsuccess = del.onerror = del.onblocked = function(){ res(); }; }); }
                      return Promise.resolve();
                    }));
                  }
                } catch(e) {}

                // Removed reload to prevent double-loads; cleanup only
              };

              // Delay until load to avoid blocking rendering
              if (document.readyState === 'complete') { cleanup(); }
              else { window.addEventListener('load', function(){ cleanup(); }); }

              // Intentionally no bfcache reload: keep current session smooth.
            })();
          `}
        </Script>
      </body>
    </html>
  );
}

