export const typewriterTags: string[] = [
	"Anger",
	"Apology",
  "Betrayal",
	"Blame",
  "Closure",
	"Confession",
  "Devotion",
  "Emptiness",
  "Fear",
	"Forgiveness",
	"Goodbye",
  "Gratitude",
  "Guilt",
  "Hate",
	"Heartbreak",
  "Hope",
  "Jealousy",
	"Love",
  "Longing",
  "Missing",
  "Nostalgia",
  "Obsession",
  "Passion",
  "Pride",
	"Regret",
	"Sadness",
  "Shame",
  "Thank You",
  "Vulnerability",
  "Yearning",
	"Other"
];

export const typewriterSubTags: Record<string, string[]> = {
  "Anger": ["angry_at_you", "angry_at_myself", "angry_at_situation", "not_angry_anymore"],
  "Apology": ["im_sorry", "you_should_be_sorry", "both_need_apologize", "im_not_sorry"],
  "Betrayal": ["you_betrayed_me", "i_betrayed_you", "mutual_betrayal", "trust_destroyed", "betrayal_by_friend"],
  "Blame": ["blame_you", "blame_myself", "both_to_blame", "no_one_to_blame"],
  "Confession": ["have_to_tell_you", "keep_secret", "i_was_wrong", "you_were_wrong", "both_made_mistakes"],
  "Devotion": ["devoted_to_you", "worship_your_existence", "you_are_my_religion", "unconditional_love", "would_die_for_you"],
  "Emptiness": ["empty_without_you", "hollow_inside", "void_in_heart", "numb_and_empty", "emptiness_consumes"],
  "Fear": ["afraid_losing_you", "afraid_commitment", "afraid_future", "not_afraid_anymore"],
  "Forgiveness": ["asking_forgiveness", "forgive_you", "cant_forgive", "forgive_myself", "need_forgive_each_other"],
  "Goodbye": ["goodbye_forever", "see_you_again", "im_leaving", "dont_leave", "need_part_ways"],
  "Gratitude": ["thank_everything", "thank_lessons", "grateful_us", "grateful_pain"],
  "Guilt": ["feel_guilty", "innocent", "you_should_guilty", "no_one_guilty", "both_guilty"],
  "Hate": ["hate_you", "hate_myself", "hate_what_we_became", "dont_hate_anymore", "i_cant_hate_you"],
  "Heartbreak": ["you_broke_heart", "broke_own_heart", "broke_each_other", "heart_healing"],
  "Hope": ["hope_for_us", "hope_you_return", "hope_for_healing", "hope_is_fading", "never_give_up_hope"],
  "Jealousy": ["jealous_of_you", "jealous_of_others", "you_jealous_of_me", "not_jealous_anymore"],
  "Love": ["love_you", "dont_love_anymore", "love_cant_be_together", "still_love", "never_loved"],
  "Longing": ["ache_for_you", "desperate_yearning", "craving_your_touch", "starving_for_you", "endless_desire"],
  "Missing": ["miss_you", "dont_miss_anymore", "miss_who_you_were", "miss_who_we_were", "miss_myself"],
  "Nostalgia": ["remember_good_times", "miss_our_past", "better_days", "golden_memories", "wish_we_could_go_back"],
  "Obsession": ["cant_stop_thinking", "consumed_by_you", "unhealthy_fixation", "obsessed_with_memories", "addicted_to_you"],
  "Passion": ["burning_desire", "wild_love", "fierce_attraction", "passionate_fire", "intense_connection"],
  "Pride": ["proud_of_us", "too_proud_to_beg", "swallowing_pride", "pride_before_fall", "damaged_pride"],
  "Regret": ["regret_everything", "no_regrets", "regret_not_trying", "regret_meeting", "both_have_regrets"],
  "Sadness": ["so_sad", "finding_happiness", "sad_what_lost", "sad_for_you", "sad_for_me"],
  "Shame": ["ashamed", "proud_myself", "you_should_ashamed", "both_should_ashamed", "no_one_ashamed"],
  "Thank You": ["thank_you", "no_thanks_needed", "thank_pain", "thank_memories", "thank_leaving"],
  "Vulnerability": ["opening_my_heart", "showing_weakness", "need_protection", "trust_you_completely", "exposed_and_fragile"],
  "Yearning": ["yearn_for_touch", "desperate_need", "soul_yearning", "yearning_for_past", "unfulfilled_yearning"],
  "Closure": ["need_answers", "dont_need_answers", "need_understand", "need_move_on", "need_closure", "never_got_closure", "seeking_closure", "closure_impossible", "found_own_closure"],
  "Other": ["other_feeling", "different_emotion", "something_else", "cant_explain", "complicated"]
};

export const typewriterPromptsBySubTag: Record<string, string[]> = {
  // Anger subcategories
  "angry_at_you": [
    "your name tastes like poison on my tongue",
    "i wake up furious that you still breathe easy",
    "every happy memory of you now feels like a slap",
    "i'm drowning in rage while you sleep peacefully",
    "you stole my peace and left me with this fire",
    "your face haunts me like a crime scene i can't leave",
    "i want to scream your name until my voice breaks",
    "you ruined the person i was and walked away smiling",
    "my anger at you is the only thing keeping me alive",
    "you broke me and i hate that part of me still wants you"
  ],
  "angry_at_myself": [
    "i gave you pieces of me i can never get back",
    "i hate that i still check if you've called",
    "i ignored every red flag like they were love notes",
    "i'm furious i wasted years on someone so careless",
    "i hate how small i made myself to fit your world",
    "i gave you my heart and you treated it like trash",
    "i'm angry i let you convince me i was the problem",
    "i hate that i still defend you to people who saw the truth",
    "i ignored my gut feeling and now i'm paying for it",
    "i'm furious at the person i became just to keep you"
  ],
  "angry_at_situation": [
    "we had everything and life took it away for nothing",
    "the timing was perfect until it wasn't",
    "i'm furious we loved each other at the wrong time",
    "fate gave us to each other then ripped us apart",
    "i'm angry the universe let us meet just to suffer",
    "we deserved better than the hand we were dealt",
    "i'm raging at a world that let us fall in love and fail",
    "life promised us forever then pulled the rug out",
    "i hate that loving you was right and wrong at once",
    "the cruelest joke is that we could've worked anywhere else"
  ],
  "not_angry_anymore": [
    "the anger faded and left me with nothing",
    "i'm too exhausted to hate you anymore",
    "rage turned to ash and i'm just empty now",
    "i don't have the energy to be mad at you",
    "my anger died and took my hope with it",
    "i'm too numb to feel fury anymore",
    "the rage burned out and left me hollow",
    "i'm past anger now, just quietly broken",
    "fury turned to fog and i can't feel anything",
    "i'm too tired to even remember why i was mad"
  ],

  // Apology subcategories
  "im_sorry": [
    "i'm sorry i wasn't what you needed me to be",
    "i'm sorry for every time i made you feel alone",
    "i'm sorry i loved you so much it suffocated us",
    "i'm sorry i stayed when leaving would've saved us both",
    "i'm sorry for all the words i should've said sooner",
    "i'm sorry i couldn't be strong enough for both of us",
    "i'm sorry i let my insecurities poison what we had",
    "i'm sorry for every promise i couldn't keep",
    "i'm sorry i made you the villain in my head",
    "i'm sorry i couldn't let you go when you needed to leave"
  ],
  "you_should_be_sorry": [
    "you owe me an apology for treating me like i was replaceable",
    "you should be sorry for making me feel crazy",
    "you need to apologize for the years i wasted waiting",
    "you owe me sorry for every lie i believed",
    "you should be sorry for making promises you knew you'd break",
    "you need to apologize for using my love against me",
    "you owe me sorry for leaving without a real goodbye",
    "you should be sorry for making me doubt my worth",
    "you need to apologize for the person you made me become",
    "you owe me sorry for walking away like i meant nothing"
  ],
  "both_need_apologize": [
    "we both broke each other in ways we can't take back",
    "i'm sorry for my part and i know you hurt too",
    "we both said things we can't unsay",
    "i'm sorry for the damage i caused and the damage you left",
    "we both failed at loving each other right",
    "i'm sorry i wasn't perfect and you weren't either",
    "we both hurt each other trying not to get hurt",
    "i'm sorry for my mistakes and yours still sting",
    "we both needed to be better than we were",
    "i'm sorry we couldn't save each other or ourselves"
  ],
  "im_not_sorry": [
    "i'm not sorry for finally choosing my own peace",
    "i'm not sorry for leaving when staying was killing me",
    "i'm not sorry for protecting what was left of my heart",
    "i'm not sorry for refusing to be your second choice",
    "i'm not sorry for walking away from someone who didn't fight for me",
    "i'm not sorry for finally loving myself more than you",
    "i'm not sorry for setting boundaries you called selfish",
    "i'm not sorry for choosing the life you said i couldn't have",
    "i'm not sorry for healing in ways that didn't include you",
    "i'm not sorry for becoming someone you no longer recognize"
  ],

  // Blame subcategories
  "blame_you": [
    "you made me believe i was too much and not enough",
    "you turned my love into something i'm ashamed of",
    "you took the best parts of me and left me with scraps",
    "you made me question if i was ever worth loving",
    "you broke me in ways i didn't know were possible",
    "you taught me that trust is just another word for stupid",
    "you made me feel like loving you was my biggest mistake",
    "you turned every memory we had into something that hurts",
    "you stole my ability to love without fear",
    "you made me hate the person i became while loving you"
  ],
  "blame_myself": [
    "i blame myself for ignoring who you really were",
    "i blame myself for believing love would be enough",
    "i blame myself for staying long after i should've left",
    "i blame myself for giving you power to destroy me",
    "i blame myself for making excuses for your behavior",
    "i blame myself for losing who i was trying to keep you",
    "i blame myself for thinking i could change you",
    "i blame myself for every time i chose you over me",
    "i blame myself for letting you convince me i was the problem",
    "i blame myself for wasting years on someone who didn't care"
  ],
  "both_to_blame": [
    "we both destroyed what could've been beautiful",
    "we both chose pride over trying to understand each other",
    "we both said hurtful things we can never take back",
    "we both stopped fighting for us at different times",
    "we both let our fears turn love into a battlefield",
    "we both broke promises we swore we'd keep",
    "we both hurt each other more than outsiders ever could",
    "we both gave up instead of growing up together",
    "we both turned love into something unrecognizable",
    "we both knew it was ending but neither stopped it"
  ],
  "no_one_to_blame": [
    "sometimes love just isn't enough and that's nobody's fault",
    "we tried our best and it still wasn't meant to be",
    "timing can kill even the strongest love",
    "we loved each other wrong but not on purpose",
    "sometimes people just aren't meant to last",
    "we outgrew each other and that's just life",
    "loving each other and being right for each other aren't the same",
    "we were both doing our best with broken pieces",
    "sometimes goodbye is no one's fault",
    "we just weren't meant to be forever and that's okay"
  ],

  // Confession subcategories
  "have_to_tell_you": [
    "i need to confess that i still dream about you every night",
    "i have to tell you that leaving you was the hardest thing i've done",
    "i need to confess that i think about you in every love song",
    "i have to tell you that i'm still in love with who you used to be",
    "i need to confess that i check your social media even though it hurts",
    "i have to tell you that i've never loved anyone the way i loved you",
    "i need to confess that i still wear the shirt you left behind",
    "i have to tell you that i saved all our messages and read them when i'm weak",
    "i need to confess that i'm not over you and i don't know if i ever will be",
    "i have to tell you that you're still the first person i want to call with good news"
  ],
  "keep_secret": [
    "i'll never tell you how many times i've driven past your house",
    "i'll keep it secret that i still have your number memorized",
    "i'll never admit that i compare everyone to you",
    "i'll keep it secret that i cry on our anniversary every year",
    "i'll never tell you that i kept every gift you gave me",
    "i'll keep it secret that i still sleep on my side of the bed",
    "i'll never admit that i pray you'll come back someday",
    "i'll keep it secret that i've never deleted our photos",
    "i'll never tell you that i still love you more than i should",
    "i'll keep it secret that you're the reason i'm afraid to love again"
  ],
  "i_was_wrong": [
    "i was wrong to think we could fix everything with love",
    "i was wrong to ignore the signs that we were falling apart",
    "i was wrong to believe you when you said you'd never leave",
    "i was wrong to think i could be enough for you",
    "i was wrong to stay when every bone in my body said go",
    "i was wrong to make you my whole world instead of just part of it",
    "i was wrong to think loving harder would make you love me back",
    "i was wrong to believe time would heal what we broke",
    "i was wrong to think we'd be different from everyone else",
    "i was wrong to give you chances you never asked for"
  ],
  "you_were_wrong": [
    "you were wrong to think i'd wait forever",
    "you were wrong to treat my love like it was guaranteed",
    "you were wrong to believe i'd always be there after you left",
    "you were wrong to think i wouldn't find someone better",
    "you were wrong to underestimate how much i could love myself",
    "you were wrong to think i needed you to be whole",
    "you were wrong to believe i'd never move on",
    "you were wrong to take my loyalty for granted",
    "you were wrong to think i'd keep breaking for you",
    "you were wrong to assume i'd always be your backup plan"
  ],
  "both_made_mistakes": [
    "we both thought love would be enough to save us",
    "we both held grudges instead of having hard conversations",
    "we both expected the other to read our minds",
    "we both kept score instead of being on the same team",
    "we both let pride stand in the way of apologizing",
    "we both chose to be right over being happy",
    "we both stopped trying when things got hard",
    "we both made promises we knew we couldn't keep",
    "we both hurt each other when we were hurting ourselves",
    "we both gave up on us at different times"
  ],

  // Fear subcategories
  "afraid_losing_you": [
    "i'm terrified you'll leave and i'll never recover",
    "i'm scared that one day you'll wake up and not love me anymore",
    "i'm afraid i'm not enough to make you stay",
    "i'm terrified of the silence after you're gone",
    "i'm scared you'll forget me faster than i can forget you",
    "i'm afraid of becoming a stranger to the person who knew me best",
    "i'm terrified you'll find someone who loves you better than i could",
    "i'm scared that losing you means losing myself",
    "i'm afraid you'll realize you never needed me at all",
    "i'm terrified that you're already one foot out the door"
  ],
  "afraid_commitment": [
    "i'm scared that forever is just another word for trapped",
    "i'm terrified of losing myself trying to be what you need",
    "i'm afraid commitment means giving up who i am",
    "i'm scared that loving you will mean losing my freedom",
    "i'm terrified of becoming someone i don't recognize for you",
    "i'm afraid that staying means settling for less than i deserve",
    "i'm scared commitment will turn our love into obligation",
    "i'm terrified of waking up one day and resenting you",
    "i'm afraid of choosing you and regretting it later",
    "i'm scared that forever with you means never with anyone else"
  ],
  "afraid_future": [
    "i'm terrified we'll outgrow each other",
    "i'm scared tomorrow will prove we were never meant to last",
    "i'm afraid the future will show us we made a mistake",
    "i'm terrified time will reveal we're not compatible",
    "i'm scared we'll become another story that didn't work out",
    "i'm afraid of investing years just to lose you anyway",
    "i'm terrified of building a life together that crumbles",
    "i'm scared the person you become won't love the person i am",
    "i'm afraid we're loving each other on borrowed time",
    "i'm terrified the future we dream about will never come"
  ],
  "not_afraid_anymore": [
    "i'm not afraid of being alone because i found myself again",
    "i'm not scared of starting over without you",
    "i'm not afraid of the future because i'm finally in control",
    "i'm not scared of losing you because i already survived it",
    "i'm not afraid of the unknown anymore, it's better than this pain",
    "i'm not scared of walking away from something that's killing me",
    "i'm not afraid of the silence because it's better than fighting",
    "i'm not scared of life without you, i'm excited for it",
    "i'm not afraid of being hurt again because i'm stronger now",
    "i'm not scared anymore because the worst already happened"
  ],

  // Forgiveness subcategories
  "asking_forgiveness": [
    "i'm begging you to forgive the person i became when i was hurting",
    "i need your forgiveness even though i don't deserve it",
    "i'm asking you to forgive me for not being brave enough to stay",
    "i need you to forgive the words i can't take back",
    "i'm pleading for forgiveness for the nights i made you cry",
    "i need you to forgive me for breaking promises i meant to keep",
    "i'm asking for grace for all the ways i failed you",
    "i need your forgiveness so i can finally forgive myself",
    "i'm begging you to forgive the damage i caused",
    "i need you to forgive me for leaving when you needed me most"
  ],
  "forgive_you": [
    "i forgive you even though it still hurts to breathe",
    "i forgive you for choosing someone else over me",
    "i forgive you for the promises you broke so easily",
    "i forgive you for making me feel like i was never enough",
    "i forgive you for leaving without fighting for us",
    "i forgive you for the lies that rewrote our entire story",
    "i forgive you for the future you stole from me",
    "i forgive you for making me doubt if i was ever loved",
    "i forgive you for walking away like i was nothing",
    "i forgive you not because you deserve it but because i need peace"
  ],
  "cant_forgive": [
    "i can't forgive how easily you replaced me",
    "i can't forgive the way you made me beg for basic decency",
    "i can't forgive that you knew you were breaking me and didn't stop",
    "i can't forgive the years you wasted pretending",
    "i can't forgive how you made me feel crazy for trusting my gut",
    "i can't forgive that you let me plan a future you never wanted",
    "i can't forgive the version of me that died loving you",
    "i can't forgive that you're fine while i'm still broken",
    "i can't forgive the lies you're still telling about us",
    "i can't forgive that you walked away without looking back"
  ],
  "forgive_myself": [
    "i need to forgive myself for loving someone who didn't love me back",
    "i'm trying to forgive myself for ignoring all the red flags",
    "i want to forgive myself for staying longer than i should have",
    "i need to forgive myself for believing someone who kept lying",
    "i'm learning to forgive myself for the years i lost",
    "i want to forgive myself for making you my entire world",
    "i need to forgive myself for not choosing me first",
    "i'm working on forgiving myself for the person i became",
    "i want to forgive myself for thinking love was enough",
    "i need to forgive myself for not leaving when i knew i should"
  ],
  "need_forgive_each_other": [
    "we both need to forgive each other for the war we waged",
    "we both need to let go of who hurt who first",
    "we both need to forgive the damage we did to each other",
    "we both need to accept we loved each other wrong",
    "we both need to forgive ourselves for not being enough",
    "we both need to stop replaying who was right and who was wrong",
    "we both need to forgive the dreams that died between us",
    "we both need to accept we failed at forever",
    "we both need to forgive each other so we can finally move on",
    "we both need to let go of the people we were together"
  ],

  // Goodbye subcategories
  "goodbye_forever": [
    "this is the last time i'll ever say your name out loud",
    "i'm closing the door on us and i won't look back",
    "goodbye to the future we'll never have",
    "this is me choosing myself for the first time",
    "i'm saying goodbye to someone who stopped fighting for me",
    "this is the final time i'll cry over you",
    "goodbye to the version of me that believed you'd change",
    "i'm done waiting for you to choose me",
    "this is me letting go of what we could've been",
    "goodbye to the person who made me feel like i wasn't enough"
  ],
  "see_you_again": [
    "maybe in another life we'll get the timing right",
    "i hope we meet again when we're both healed",
    "maybe someday we'll be strangers who once loved deeply",
    "i'll see you in memories i'm not ready to let go of yet",
    "maybe in another timeline we work out",
    "i hope our paths cross when we're better versions of ourselves",
    "maybe we'll laugh about this pain someday",
    "i'll see you in the what-ifs that haunt me",
    "maybe fate will bring us back when we're ready",
    "i hope you remember me fondly when you think of us"
  ],
  "im_leaving": [
    "i'm leaving because staying is killing me slowly",
    "i'm walking away from the person who forgot my worth",
    "i'm leaving the cage i built around my heart for you",
    "i'm done fighting for someone who won't fight for me",
    "i'm leaving before there's nothing left of me to save",
    "i'm walking away from love that hurts more than heals",
    "i'm leaving the version of me that begged for your attention",
    "i'm done sacrificing my peace for your comfort",
    "i'm leaving this toxicity disguised as love",
    "i'm walking away from someone who made me feel small"
  ],
  "dont_leave": [
    "please don't leave, i'm still learning how to love you right",
    "i'm begging you to stay and fight for us one more time",
    "please don't go, i can't survive losing you",
    "stay, please, i'll be better i swear",
    "don't leave me here drowning in the silence",
    "i'm not ready to let you become a memory",
    "please stay, i'll change everything you hate about me",
    "don't go, i don't know who i am without you",
    "please give us one more chance to get it right",
    "stay, because losing you will break me beyond repair"
  ],
  "need_part_ways": [
    "i need to leave so we can both find ourselves again",
    "we need to part ways before we destroy each other completely",
    "i need to walk away before i lose myself entirely",
    "we need to say goodbye so we can both start healing",
    "i need to let you go even though it's tearing me apart",
    "we need to separate before our love turns to hate",
    "i need to leave because loving you is costing me myself",
    "we need to part ways before there's nothing left to save",
    "i need to walk away to remember who i was before you",
    "we need to end this before we both become unrecognizable"
  ],

  // Gratitude subcategories
  "thank_everything": [
    "thank you for loving me even if it wasn't forever",
    "i'm grateful for every moment even the ones that hurt",
    "thank you for showing me what love could feel like",
    "i'm grateful we had what we had while it lasted",
    "thank you for the memories i'll carry forever",
    "i'm grateful you were mine even if just for a while",
    "thank you for teaching me how to love deeply",
    "i'm grateful for the dreams we shared even if they died",
    "thank you for the laughter before the tears",
    "i'm grateful our paths crossed even if they had to part"
  ],
  "thank_lessons": [
    "thank you for teaching me what i deserve and what i don't",
    "i'm grateful you showed me my own strength",
    "thank you for the lessons that hurt but made me wiser",
    "i'm grateful you taught me how to let go",
    "thank you for showing me what love shouldn't look like",
    "i'm grateful you forced me to choose myself",
    "thank you for the pain that led to growth",
    "i'm grateful you taught me i can survive anything",
    "thank you for showing me i'm stronger than i thought",
    "i'm grateful for the truth even though it broke me"
  ],
  "grateful_us": [
    "i'm grateful we tried even though we failed",
    "thank you for being my person even if not forever",
    "i'm grateful for the love we built even though it crumbled",
    "thank you for making me believe in us",
    "i'm grateful for the version of us that felt invincible",
    "thank you for the future we planned even if it never came",
    "i'm grateful we loved each other the best we could",
    "thank you for the team we were before we fell apart",
    "i'm grateful for what we had before it turned to pain",
    "thank you for loving me in the only way you knew how"
  ],
  "grateful_pain": [
    "i'm grateful for the heartbreak that taught me my worth",
    "thank you for the pain that forced me to heal",
    "i'm grateful for the tears that washed away my illusions",
    "thank you for breaking me so i could rebuild myself stronger",
    "i'm grateful for the suffering that revealed who i really am",
    "thank you for the emptiness that taught me to fill myself",
    "i'm grateful for the loneliness that made me whole",
    "thank you for the darkness that showed me my own light",
    "i'm grateful for the wounds that became my armor",
    "thank you for leaving because it taught me i don't need you"
  ],

  // Guilt subcategories
  "feel_guilty": [
    "i feel guilty for everything",
    "i feel guilty for hurting you",
    "i feel guilty for not trying harder",
    "i feel guilty for my mistakes",
    "i feel guilty for my choices",
    "i feel guilty for my weakness",
    "i feel guilty for my selfishness",
    "i feel guilty for my stubbornness",
    "i feel guilty for my pride",
    "i feel guilty for my fear"
  ],
  "innocent": [
    "i know i'm innocent in this",
    "i know i did nothing wrong",
    "i know i'm not to blame",
    "i know i'm not responsible",
    "i know i'm not guilty",
    "i know i'm not at fault",
    "i know i'm not the problem",
    "i know i'm not the cause",
    "i know i'm not the reason",
    "i know i'm not the one"
  ],
  "you_should_guilty": [
    "i think you should feel guilty",
    "i think you should feel ashamed",
    "i think you should feel bad",
    "i think you should feel responsible",
    "i think you should feel at fault",
    "i think you should feel blame",
    "i think you should feel remorse",
    "i think you should feel regret",
    "i think you should feel sorry",
    "i think you should feel pain"
  ],
  "no_one_guilty": [
    "i don't think anyone is guilty",
    "i don't think anyone is to blame",
    "i don't think anyone is at fault",
    "i don't think anyone is responsible",
    "i don't think anyone should feel bad",
    "i don't think anyone should feel guilty",
    "i don't think anyone should feel ashamed",
    "i don't think anyone should feel remorse",
    "i don't think anyone should feel regret",
    "i don't think anyone should feel pain"
  ],
  "both_guilty": [
    "i think we're both guilty",
    "i think we're both to blame",
    "i think we're both at fault",
    "i think we're both responsible",
    "i think we both made mistakes",
    "i think we both failed each other",
    "i think we both hurt each other",
    "i think we both broke each other",
    "i think we both destroyed us",
    "i think we both ruined everything"
  ],

  // Hate subcategories
  "hate_you": [
    "i hate you for everything you did",
    "i hate you for breaking my heart",
    "i hate you for leaving me alone",
    "i hate you for the pain you caused",
    "i hate you for the lies you told",
    "i hate you for the betrayal",
    "i hate you for the emptiness",
    "i hate you for the loneliness",
    "i hate you for the tears",
    "i hate you for the brokenness"
  ],
  "hate_myself": [
    "i hate myself for loving you",
    "i hate myself for staying so long",
    "i hate myself for believing you",
    "i hate myself for not leaving sooner",
    "i hate myself for my weakness",
    "i hate myself for my stupidity",
    "i hate myself for my blindness",
    "i hate myself for my choices",
    "i hate myself for my pain",
    "i hate myself for my heartbreak"
  ],
  "hate_what_we_became": [
    "i hate what we turned into",
    "i hate the mess we created",
    "i hate what we became together",
    "i hate the toxic thing we built",
    "i hate what we allowed ourselves to be",
    "i hate the people we became",
    "i hate the relationship we had",
    "i hate the love we destroyed",
    "i hate the future we ruined",
    "i hate the life we wasted"
  ],
  "dont_hate_anymore": [
    "i don't hate you anymore",
    "i'm too tired to hate you",
    "i don't have energy for hate",
    "i'm done with hating you",
    "i'm over the hate",
    "i don't feel hate anymore",
    "i'm too broken to hate",
    "i'm too empty to hate",
    "i'm too numb to hate",
    "i'm too dead inside to hate"
  ],
  "i_cant_hate_you": [
    "i can't bring myself to hate you",
    "i want to hate you but i can't",
    "i try to hate you but i can't",
    "i wish i could hate you",
    "i should hate you but i don't",
    "i want to hate you so badly",
    "i need to hate you to heal",
    "i want to hate you to move on",
    "i should hate you for what you did",
    "i want to hate you for my own good"
  ],

  // Heartbreak subcategories
  "you_broke_heart": [
    "i feel like you broke my heart",
    "i think you shattered my soul",
    "i believe you destroyed my love",
    "i feel like you killed my hope",
    "i think you broke my spirit",
    "i believe you crushed my dreams",
    "i feel like you stole my future",
    "i think you took my happiness",
    "i believe you destroyed my peace",
    "i feel like you broke everything"
  ],
  "broke_own_heart": [
    "i think i broke my own heart",
    "i believe i destroyed my own love",
    "i feel like i killed my own hope",
    "i think i broke my own spirit",
    "i believe i crushed my own dreams",
    "i feel like i stole my own future",
    "i think i took my own happiness",
    "i believe i destroyed my own peace",
    "i feel like i broke everything",
    "i think i ruined my own life"
  ],
  "broke_each_other": [
    "i think we broke each other's hearts",
    "i believe we destroyed each other's love",
    "i feel like we killed each other's hope",
    "i think we broke each other's spirits",
    "i believe we crushed each other's dreams",
    "i feel like we stole each other's future",
    "i think we took each other's happiness",
    "i believe we destroyed each other's peace",
    "i feel like we broke everything",
    "i think we ruined each other's lives"
  ],
  "heart_healing": [
    "i think my heart is slowly healing",
    "i believe i'm getting better",
    "i feel like i'm starting to heal",
    "i think my heart is mending",
    "i believe i'm finding peace",
    "i feel like i'm moving forward",
    "i think my heart is growing stronger",
    "i believe i'm learning to love again",
    "i feel like i'm finding hope again",
    "i think my heart is beating again"
  ],

  // Jealousy subcategories
  "jealous_of_you": [
    "i'm jealous of your happiness",
    "i'm jealous of your freedom",
    "i'm jealous of your new life",
    "i'm jealous of your ability to move on",
    "i'm jealous of your peace",
    "i'm jealous of your strength",
    "i'm jealous of your independence",
    "i'm jealous of your future",
    "i'm jealous of your choices",
    "i'm jealous of your courage"
  ],
  "jealous_of_others": [
    "i'm jealous of people who have love",
    "i'm jealous of happy couples",
    "i'm jealous of people who don't know pain",
    "i'm jealous of those who found happiness",
    "i'm jealous of people who don't understand heartbreak",
    "i'm jealous of people who have what i want",
    "i'm jealous of people who don't know loneliness",
    "i'm jealous of those who have hope",
    "i'm jealous of people who have peace",
    "i'm jealous of those who have love"
  ],
  "you_jealous_of_me": [
    "i think you're jealous of my strength",
    "i believe you're jealous of my independence",
    "i feel like you're jealous of my peace",
    "i think you're jealous of my future",
    "i believe you're jealous of my choices",
    "i feel like you're jealous of my courage",
    "i think you're jealous of my happiness",
    "i believe you're jealous of my freedom",
    "i feel like you're jealous of my life",
    "i think you're jealous of my growth"
  ],
  "not_jealous_anymore": [
    "i'm not jealous of anything anymore",
    "i don't feel jealousy towards anyone",
    "i'm over being jealous of others",
    "i don't care about what others have",
    "i'm content with my own life",
    "i don't compare myself to others",
    "i'm happy with what i have",
    "i don't want what others have",
    "i'm grateful for my own journey",
    "i don't feel envy anymore"
  ],

  // Love subcategories
  "love_you": [
    "i love you more than words can say",
    "i love you with all my heart",
    "i love you more than life itself",
    "i love you beyond reason or logic",
    "i love you with every fiber of my being",
    "i love you more than the stars love the night",
    "i love you more than the ocean loves the shore",
    "i love you more than the sun loves the sky",
    "i love you more than the earth loves the moon",
    "i love you more than anything in this world"
  ],
  "dont_love_anymore": [
    "i don't love you like i used to",
    "i don't love you anymore",
    "i don't feel love for you",
    "i don't love you the same way",
    "i don't love you at all",
    "i don't love you anymore",
    "i don't feel anything for you",
    "i don't love you like before",
    "i don't love you anymore",
    "i don't love you the way i should"
  ],
  "love_cant_be_together": [
    "i love you but we can't be together",
    "i love you but it's not enough",
    "i love you but we're not meant to be",
    "i love you but we're too different",
    "i love you but we're too broken",
    "i love you but we're too damaged",
    "i love you but we're too hurt",
    "i love you but we're too scarred",
    "i love you but we're too wounded",
    "i love you but we're too damaged"
  ],
  "still_love": [
    "i still love you despite everything",
    "i still love you even now",
    "i still love you after all this time",
    "i still love you despite the pain",
    "i still love you despite the hurt",
    "i still love you despite the lies",
    "i still love you despite the betrayal",
    "i still love you despite the heartbreak",
    "i still love you despite the emptiness",
    "i still love you despite the loneliness"
  ],
  "never_loved": [
    "i never really loved you",
    "i never truly loved you",
    "i never actually loved you",
    "i never really felt love for you",
    "i never truly felt love for you",
    "i never actually felt love for you",
    "i never really knew what love was",
    "i never truly knew what love was",
    "i never actually knew what love was",
    "i never really understood love"
  ],

  // Missing subcategories
  "miss_you": [
    "i miss you every single day",
    "i miss you in my dreams",
    "i miss you in my thoughts",
    "i miss you in my memories",
    "i miss you in my heart",
    "i miss you in my soul",
    "i miss you in my future",
    "i miss you in my past",
    "i miss you in my present",
    "i miss you in my life"
  ],
  "dont_miss_anymore": [
    "i don't miss you anymore",
    "i don't miss you like i used to",
    "i don't miss you at all",
    "i'm over missing you",
    "i'm done missing you",
    "i don't feel missing you",
    "i don't think about missing you",
    "i don't care about missing you",
    "i don't want to miss you",
    "i don't need to miss you"
  ],
  "miss_who_you_were": [
    "i miss the person you used to be",
    "i miss the version of you i loved",
    "i miss who you were before",
    "i miss the person you pretended to be",
    "i miss the you that never existed",
    "i miss the you i thought i knew",
    "i miss the you i fell in love with",
    "i miss the you i trusted completely",
    "i miss the you i believed in",
    "i miss the you i thought was real"
  ],
  "miss_who_we_were": [
    "i miss the couple we used to be",
    "i miss the us that felt invincible",
    "i miss the relationship we had",
    "i miss the dynamic we shared",
    "i miss the team we used to be",
    "i miss the love we used to have",
    "i miss the future we used to plan",
    "i miss the dreams we used to share",
    "i miss the life we used to build",
    "i miss the happiness we used to know"
  ],
  "miss_myself": [
    "i miss the person i was before you",
    "i miss who i used to be",
    "i miss the me that existed before this",
    "i miss my old self",
    "i miss the person i lost along the way",
    "i miss the me that was happy",
    "i miss the me that was whole",
    "i miss the me that was confident",
    "i miss the me that was independent",
    "i miss the me that was free"
  ],

  // Regret subcategories
  "regret_everything": [
    "i regret everything about us",
    "i regret every choice i made",
    "i regret every word i said",
    "i regret every action i took",
    "i regret every moment we shared",
    "i regret every memory we created",
    "i regret every dream we dreamed",
    "i regret every plan we made",
    "i regret every hope we had",
    "i regret every love we shared"
  ],
  "no_regrets": [
    "i don't regret anything about us",
    "i don't regret any choice i made",
    "i don't regret any word i said",
    "i don't regret any action i took",
    "i don't regret any moment we shared",
    "i don't regret any memory we created",
    "i don't regret any dream we dreamed",
    "i don't regret any plan we made",
    "i don't regret any hope we had",
    "i don't regret any love we shared"
  ],
  "regret_not_trying": [
    "i regret not trying harder for us",
    "i regret not fighting harder for us",
    "i regret not giving more effort",
    "i regret not putting in more work",
    "i regret not trying to save us",
    "i regret not fighting for our love",
    "i regret not working harder",
    "i regret not giving my all",
    "i regret not trying everything",
    "i regret not fighting everything"
  ],
  "regret_meeting": [
    "i regret the day i met you",
    "i regret ever knowing you",
    "i regret our paths crossing",
    "i regret the moment we met",
    "i regret the day we became friends",
    "i regret the day we fell in love",
    "i regret the day we started dating",
    "i regret the day we moved in together",
    "i regret the day we got married",
    "i regret the day we said i do"
  ],
  "both_have_regrets": [
    "i think we both have regrets",
    "i believe we both made mistakes",
    "i feel like we both failed each other",
    "i think we both have things we'd change",
    "i believe we both have things we'd do differently",
    "i feel like we both have things we'd undo",
    "i think we both have things we'd redo",
    "i believe we both have things we'd fix",
    "i feel like we both have things we'd improve",
    "i think we both have things we'd correct"
  ],

  // Sadness subcategories
  "so_sad": [
    "i'm so sad all the time",
    "i'm so sad about everything",
    "i'm so sad about what we lost",
    "i'm so sad about what we could have been",
    "i'm so sad about what we won't be",
    "i'm so sad about the future we planned",
    "i'm so sad about the dreams we shared",
    "i'm so sad about the love we lost",
    "i'm so sad about the memories we won't make",
    "i'm so sad about the life we won't live"
  ],
  "finding_happiness": [
    "i'm trying to find happiness again",
    "i'm looking for happiness in new places",
    "i'm searching for happiness within myself",
    "i'm working on finding happiness",
    "i'm learning to be happy again",
    "i'm discovering happiness in small things",
    "i'm finding happiness in new experiences",
    "i'm creating happiness for myself",
    "i'm building happiness from scratch",
    "i'm choosing happiness every day"
  ],
  "sad_what_lost": [
    "i'm sad about what we could have been",
    "i'm sad about the future we planned",
    "i'm sad about the dreams we shared",
    "i'm sad about the love we lost",
    "i'm sad about the memories we won't make",
    "i'm sad about the life we won't live",
    "i'm sad about the happiness we won't know",
    "i'm sad about the peace we won't find",
    "i'm sad about the trust we won't rebuild",
    "i'm sad about the bond we won't restore"
  ],
  "sad_for_you": [
    "i'm sad about what you're missing",
    "i'm sad for the person you could have been",
    "i'm sad about the choices you made",
    "i'm sad for the pain you're in",
    "i'm sad for the life you're living",
    "i'm sad for the future you won't have",
    "i'm sad for the dreams you won't achieve",
    "i'm sad for the love you won't experience",
    "i'm sad for the happiness you won't know",
    "i'm sad for the peace you won't find"
  ],
  "sad_for_me": [
    "i'm sad about what i lost",
    "i'm sad for the person i became",
    "i'm sad about the time i wasted",
    "i'm sad for the love i gave away",
    "i'm sad for the future i lost",
    "i'm sad for the dreams i abandoned",
    "i'm sad for the happiness i sacrificed",
    "i'm sad for the peace i destroyed",
    "i'm sad for the trust i broke",
    "i'm sad for the bond i damaged"
  ],

  // Shame subcategories
  "ashamed": [
    "i feel ashamed of everything",
    "i feel ashamed of who i became",
    "i feel ashamed of my choices",
    "i feel ashamed of my actions",
    "i feel ashamed of my words",
    "i feel ashamed of my mistakes",
    "i feel ashamed of my weakness",
    "i feel ashamed of my stupidity",
    "i feel ashamed of my blindness",
    "i feel ashamed of my pain"
  ],
  "proud_myself": [
    "i'm proud of how far i've come",
    "i'm proud of my strength",
    "i'm proud of my ability to heal",
    "i'm proud of who i've become",
    "i'm proud of my resilience",
    "i'm proud of my courage",
    "i'm proud of my independence",
    "i'm proud of my growth",
    "i'm proud of my wisdom",
    "i'm proud of my survival"
  ],
  "you_should_ashamed": [
    "i think you should be ashamed",
    "i believe you should feel ashamed",
    "i feel like you should be ashamed",
    "i think you should feel guilty",
    "i believe you should feel bad",
    "i feel like you should feel remorse",
    "i think you should feel regret",
    "i believe you should feel sorry",
    "i feel like you should feel pain",
    "i think you should feel hurt"
  ],
  "both_should_ashamed": [
    "i think we both should be ashamed",
    "i believe we both should feel ashamed",
    "i feel like we both should be ashamed",
    "i think we both should feel guilty",
    "i believe we both should feel bad",
    "i feel like we both should feel remorse",
    "i think we both should feel regret",
    "i believe we both should feel sorry",
    "i feel like we both should feel pain",
    "i think we both should feel hurt"
  ],
  "no_one_ashamed": [
    "i don't think anyone should be ashamed",
    "i don't believe anyone should feel ashamed",
    "i don't feel like anyone should be ashamed",
    "i don't think anyone should feel guilty",
    "i don't believe anyone should feel bad",
    "i don't feel like anyone should feel remorse",
    "i don't think anyone should feel regret",
    "i don't believe anyone should feel sorry",
    "i don't feel like anyone should feel pain",
    "i don't think anyone should feel hurt"
  ],

  // Thank You subcategories
  "thank_you": [
    "i want to thank you for everything",
    "i want to thank you for the memories",
    "i want to thank you for the love",
    "i want to thank you for the lessons",
    "i want to thank you for the growth",
    "i want to thank you for the strength",
    "i want to thank you for the wisdom",
    "i want to thank you for the courage",
    "i want to thank you for the independence",
    "i want to thank you for the freedom"
  ],
  "no_thanks_needed": [
    "i don't need you to thank me",
    "i don't want you to thank me",
    "i don't expect you to thank me",
    "i don't require you to thank me",
    "i don't ask you to thank me",
    "i don't demand you to thank me",
    "i don't insist you to thank me",
    "i don't force you to thank me",
    "i don't pressure you to thank me",
    "i don't compel you to thank me"
  ],
  "thank_pain": [
    "i want to thank you for the pain",
    "i want to thank you for the hurt",
    "i want to thank you for the suffering",
    "i want to thank you for the wounds",
    "i want to thank you for the heartbreak",
    "i want to thank you for the tears",
    "i want to thank you for the loneliness",
    "i want to thank you for the emptiness",
    "i want to thank you for the darkness",
    "i want to thank you for the brokenness"
  ],
  "thank_memories": [
    "i want to thank you for the memories",
    "i want to thank you for the moments",
    "i want to thank you for the experiences",
    "i want to thank you for the stories",
    "i want to thank you for the adventures",
    "i want to thank you for the laughter",
    "i want to thank you for the joy",
    "i want to thank you for the happiness",
    "i want to thank you for the peace",
    "i want to thank you for the love"
  ],
  "thank_leaving": [
    "i want to thank you for leaving",
    "i want to thank you for walking away",
    "i want to thank you for setting me free",
    "i want to thank you for ending it",
    "i want to thank you for the closure",
    "i want to thank you for the freedom",
    "i want to thank you for the independence",
    "i want to thank you for the strength",
    "i want to thank you for the courage",
    "i want to thank you for the wisdom"
  ],

  // Closure subcategories
  "need_answers": [
    "i need answers to move forward",
    "i need to understand what happened",
    "i need to know why you left",
    "i need to know what went wrong",
    "i need to know the truth",
    "i need to know the reason",
    "i need to know the cause",
    "i need to know the explanation",
    "i need to know the motivation",
    "i need to know the purpose"
  ],
  "dont_need_answers": [
    "i don't need answers anymore",
    "i don't need to know why",
    "i don't need explanations",
    "i don't need the truth",
    "i don't need the reason",
    "i don't need the cause",
    "i don't need the explanation",
    "i don't need the motivation",
    "i don't need the purpose",
    "i don't need anything from you"
  ],
  "need_understand": [
    "i need to understand what happened",
    "i need to understand why you left",
    "i need to understand where we went wrong",
    "i need to understand to move on",
    "i need to understand to heal",
    "i need to understand to grow",
    "i need to understand to learn",
    "i need to understand to forgive",
    "i need to understand to accept",
    "i need to understand to let go"
  ],
  "need_move_on": [
    "i need to move on from this",
    "i need to let go and move forward",
    "i need to leave this behind me",
    "i need to move on to better things",
    "i need to move on for my own sake",
    "i need to move on to heal",
    "i need to move on to grow",
    "i need to move on to learn",
    "i need to move on to forgive",
    "i need to move on to accept"
  ],
  "need_closure": [
    "i need closure to move forward",
    "i need closure to heal properly",
    "i need closure to find peace",
    "i need closure to let go",
    "i need closure to end this chapter",
    "i need closure to start over",
    "i need closure to rebuild",
    "i need closure to restore",
    "i need closure to renew",
    "i need closure to regenerate"
  ],
  "never_got_closure": [
    "i never got the closure i needed",
    "i never got the answers i wanted",
    "i never got the explanation i deserved",
    "i never got the truth i needed",
    "i never got the reason i wanted",
    "i never got the cause i deserved",
    "i never got the motivation i needed",
    "i never got the purpose i wanted",
    "i never got the understanding i deserved",
    "i never got the peace i needed"
  ],
  "seeking_closure": [
    "i'm actively seeking closure",
    "i'm searching for closure everywhere",
    "i'm looking for closure in any way",
    "i'm pursuing closure actively",
    "i'm hunting for closure desperately",
    "i'm seeking closure constantly",
    "i'm searching for closure endlessly",
    "i'm looking for closure hopelessly",
    "i'm pursuing closure painfully",
    "i'm hunting for closure desperately"
  ],
  "closure_impossible": [
    "i think closure is impossible",
    "i believe closure is out of reach",
    "i feel like closure is unattainable",
    "i think closure is hopeless",
    "i believe closure is unachievable",
    "i feel like closure is unrealistic",
    "i think closure is impractical",
    "i believe closure is unfeasible",
    "i feel like closure is unworkable",
    "i think closure is undoable"
  ],
  "found_own_closure": [
    "i found my own closure",
    "i created my own closure",
    "i made my own closure",
    "i built my own closure",
    "i established my own closure",
    "i formed my own closure",
    "i developed my own closure",
    "i constructed my own closure",
    "i fashioned my own closure",
    "i shaped my own closure"
  ],

  // Other subcategories
  "other_feeling": [
    "i feel something i can't name",
    "i feel something i can't describe",
    "i feel something i can't explain",
    "i feel something i can't understand",
    "i feel something i can't categorize",
    "i feel something i can't label",
    "i feel something i can't identify",
    "i feel something i can't recognize",
    "i feel something i can't place",
    "i feel something i can't define"
  ],
  "different_emotion": [
    "i feel a different emotion now",
    "i feel something completely different",
    "i feel something unexpected",
    "i feel something surprising",
    "i feel something new",
    "i feel something strange",
    "i feel something unusual",
    "i feel something unfamiliar",
    "i feel something unknown",
    "i feel something foreign"
  ],
  "something_else": [
    "i feel like there's something else",
    "i think there's something deeper",
    "i believe there's something more",
    "i feel like there's something hidden",
    "i think there's something beneath",
    "i believe there's something underneath",
    "i feel like there's something concealed",
    "i think there's something covered",
    "i believe there's something masked",
    "i feel like there's something disguised"
  ],
  "cant_explain": [
    "i can't explain what i'm feeling",
    "i can't put my feelings into words",
    "i can't describe what i'm experiencing",
    "i can't articulate my emotions",
    "i can't express what i'm feeling",
    "i can't communicate my feelings",
    "i can't convey what i'm experiencing",
    "i can't put words to my emotions",
    "i can't verbalize my feelings",
    "i can't speak my emotions"
  ],
  "complicated": [
    "i feel like this is complicated",
    "i think this is complex",
    "i believe this is intricate",
    "i feel like this is involved",
    "i think this is elaborate",
    "i believe this is sophisticated",
    "i feel like this is detailed",
    "i think this is thorough",
    "i believe this is comprehensive",
    "i feel like this is extensive"
  ],

  // Devotion subcategories
  "devoted_to_you": [
    "i'm completely devoted to you",
    "i'm totally devoted to you",
    "i'm entirely devoted to you",
    "i'm wholly devoted to you",
    "i'm fully devoted to you",
    "i'm completely committed to you",
    "i'm totally committed to you",
    "i'm entirely committed to you",
    "i'm wholly committed to you",
    "i'm fully committed to you"
  ],
  "worship_your_existence": [
    "i worship your existence completely",
    "i worship your being totally",
    "i worship your presence entirely",
    "i worship your essence wholly",
    "i worship your soul fully",
    "i worship your spirit completely",
    "i worship your heart totally",
    "i worship your mind entirely",
    "i worship your body wholly",
    "i worship your life fully"
  ],
  "you_are_my_religion": [
    "i think you are my religion",
    "i believe you are my faith",
    "i feel like you are my god",
    "i think you are my salvation",
    "i believe you are my temple",
    "i feel like you are my church",
    "i think you are my prayer",
    "i believe you are my scripture",
    "i feel like you are my hymn",
    "i think you are my altar"
  ],
  "unconditional_love": [
    "i love you unconditionally",
    "i love you without conditions",
    "i love you without limits",
    "i love you without boundaries",
    "i love you without restrictions",
    "i love you without requirements",
    "i love you without expectations",
    "i love you without demands",
    "i love you without rules",
    "i love you without conditions"
  ],
  "would_die_for_you": [
    "i would die for you",
    "i would sacrifice everything for you",
    "i would give my life for you",
    "i would lay down my life for you",
    "i would risk everything for you",
    "i would lose everything for you",
    "i would abandon everything for you",
    "i would forsake everything for you",
    "i would renounce everything for you",
    "i would surrender everything for you"
  ],

  // Hope subcategories
  "hope_for_us": [
    "i still have hope for us",
    "i hope we can fix this",
    "i hope we can start over",
    "i hope we can find our way back",
    "i hope we can heal together",
    "i hope we can love again",
    "i hope we can trust again",
    "i hope we can forgive each other",
    "i hope we can grow together",
    "i hope we can be happy again"
  ],
  "hope_you_return": [
    "i hope you come back to me",
    "i hope you realize what you lost",
    "i hope you remember what we had",
    "i hope you find your way home",
    "i hope you choose me again",
    "i hope you miss me too",
    "i hope you want me back",
    "i hope you need me again",
    "i hope you love me still",
    "i hope you want us again"
  ],
  "hope_for_healing": [
    "i hope we both find peace",
    "i hope time heals our wounds",
    "i hope we both learn to love again",
    "i hope we both find happiness",
    "i hope we both heal completely",
    "i hope we both find ourselves again",
    "i hope we both grow stronger",
    "i hope we both find hope again",
    "i hope we both find love again",
    "i hope we both find peace again"
  ],
  "hope_is_fading": [
    "i feel like my hope is fading",
    "i think hope is leaving me",
    "i believe hope is dying slowly",
    "i feel like hope is slipping away",
    "i think hope is becoming harder to hold",
    "i believe hope is running out",
    "i feel like hope is disappearing",
    "i think hope is becoming distant",
    "i believe hope is becoming impossible",
    "i feel like hope is becoming a dream"
  ],
  "never_give_up_hope": [
    "i will never give up hope",
    "i will never stop believing in us",
    "i will never stop hoping for love",
    "i will never stop hoping for happiness",
    "i will never stop hoping for peace",
    "i will never stop hoping for healing",
    "i will never stop hoping for tomorrow",
    "i will never stop hoping for better days",
    "i will never stop hoping for love again",
    "i will never stop hoping for us again"
  ],

  // Longing subcategories
  "ache_for_you": [
    "i ache for you every single day",
    "i ache for you in my bones",
    "i ache for you in my heart",
    "i ache for you in my soul",
    "i ache for you in my dreams",
    "i ache for you in my thoughts",
    "i ache for you in my memories",
    "i ache for you in my future",
    "i ache for you in my past",
    "i ache for you in my present"
  ],
  "desperate_yearning": [
    "i yearn for you desperately",
    "i yearn for you every moment",
    "i yearn for you with all my heart",
    "i yearn for you with all my soul",
    "i yearn for you with all my being",
    "i yearn for you constantly",
    "i yearn for you endlessly",
    "i yearn for you hopelessly",
    "i yearn for you painfully",
    "i yearn for you completely"
  ],
  "craving_your_touch": [
    "i crave your touch constantly",
    "i crave your touch desperately",
    "i crave your touch endlessly",
    "i crave your touch painfully",
    "i crave your touch hopelessly",
    "i crave your touch completely",
    "i crave your touch totally",
    "i crave your touch absolutely",
    "i crave your touch entirely",
    "i crave your touch wholly"
  ],
  "starving_for_you": [
    "i'm starving for your love",
    "i'm starving for your presence",
    "i'm starving for your touch",
    "i'm starving for your voice",
    "i'm starving for your smile",
    "i'm starving for your laughter",
    "i'm starving for your warmth",
    "i'm starving for your comfort",
    "i'm starving for your peace",
    "i'm starving for your happiness"
  ],
  "endless_desire": [
    "i have endless desire for you",
    "i feel endless desire for you",
    "i experience endless desire for you",
    "i live with endless desire for you",
    "i carry endless desire for you",
    "i hold endless desire for you",
    "i keep endless desire for you",
    "i nurture endless desire for you",
    "i feed endless desire for you",
    "i grow endless desire for you"
  ],

  // Nostalgia subcategories
  "remember_good_times": [
    "i remember when love was easy",
    "i remember when we were happy",
    "i remember when we were whole",
    "i remember when we were together",
    "i remember when we were in love",
    "i remember when we were free",
    "i remember when we were young",
    "i remember when we were innocent",
    "i remember when we were hopeful",
    "i remember when we were alive"
  ],
  "miss_our_past": [
    "i miss the people we used to be",
    "i miss the life we built together",
    "i miss the dreams we shared",
    "i miss the way we used to love",
    "i miss the past version of us",
    "i miss the future we planned",
    "i miss the happiness we knew",
    "i miss the peace we had",
    "i miss the trust we shared",
    "i miss the bond we formed"
  ],
  "better_days": [
    "i remember better days than these",
    "i remember when everything was easier",
    "i remember when life was simpler",
    "i remember when love was enough",
    "i remember when we were happy",
    "i remember when we were whole",
    "i remember when we were together",
    "i remember when we were in love",
    "i remember when we were free",
    "i remember when we were hopeful"
  ],
  "golden_memories": [
    "i cherish our golden memories",
    "i hold our golden memories close",
    "i treasure our golden memories",
    "i protect our golden memories",
    "i keep our golden memories safe",
    "i love our golden memories",
    "i miss our golden memories",
    "i need our golden memories",
    "i want our golden memories",
    "i live for our golden memories"
  ],
  "wish_we_could_go_back": [
    "i wish we could go back to the beginning",
    "i wish we could rewind and start over",
    "i wish we could go back to when love was enough",
    "i wish we could go back to simpler times",
    "i wish we could go back and do it right",
    "i wish we could go back to when we were happy",
    "i wish we could go back to when we were whole",
    "i wish we could go back to when we were together",
    "i wish we could go back to when we were in love",
    "i wish we could go back to when we were free"
  ],

  // Vulnerability subcategories
  "opening_my_heart": [
    "i'm opening my heart to you",
    "i'm showing you my heart",
    "i'm giving you my heart",
    "i'm sharing my heart with you",
    "i'm revealing my heart to you",
    "i'm exposing my heart to you",
    "i'm baring my heart to you",
    "i'm offering my heart to you",
    "i'm presenting my heart to you",
    "i'm displaying my heart to you"
  ],
  "showing_weakness": [
    "i'm showing you my weakness",
    "i'm revealing my weakness to you",
    "i'm exposing my weakness to you",
    "i'm sharing my weakness with you",
    "i'm giving you my weakness",
    "i'm offering you my weakness",
    "i'm presenting you my weakness",
    "i'm displaying you my weakness",
    "i'm baring you my weakness",
    "i'm showing you my vulnerability"
  ],
  "need_protection": [
    "i need you to protect me",
    "i need you to protect my heart",
    "i need you to protect my soul",
    "i need you to protect my feelings",
    "i need you to protect my emotions",
    "i need you to protect my thoughts",
    "i need you to protect my dreams",
    "i need you to protect my hopes",
    "i need you to protect my future",
    "i need you to protect my past"
  ],
  "trust_you_completely": [
    "i trust you completely",
    "i trust you with everything",
    "i trust you with my heart",
    "i trust you with my soul",
    "i trust you with my life",
    "i trust you with my future",
    "i trust you with my past",
    "i trust you with my present",
    "i trust you with my dreams",
    "i trust you with my hopes"
  ],
  "exposed_and_fragile": [
    "i feel exposed and fragile",
    "i feel vulnerable and weak",
    "i feel open and defenseless",
    "i feel naked and unprotected",
    "i feel bare and unguarded",
    "i feel transparent and see-through",
    "i feel revealed and uncovered",
    "i feel uncovered and unprotected",
    "i feel defenseless and weak",
    "i feel fragile and breakable"
  ],

  // Betrayal subcategories
  "you_betrayed_me": [
    "i trusted you with my heart",
    "i gave you my deepest secrets",
    "i believed every word you said",
    "i thought you were different",
    "i never saw it coming",
    "i opened my soul to you",
    "i let you see my weakness",
    "i thought you were safe",
    "i trusted you completely",
    "i never thought you'd hurt me"
  ],
  "i_betrayed_you": [
    "i broke your trust completely",
    "i betrayed everything we had",
    "i destroyed what we built",
    "i stabbed you in the back",
    "i became someone i hate",
    "i broke my own promises",
    "i betrayed your love",
    "i destroyed our future",
    "i broke your heart",
    "i betrayed myself too"
  ],
  "mutual_betrayal": [
    "i betrayed you and you betrayed me",
    "i broke your trust and you broke mine",
    "i destroyed us and so did you",
    "i betrayed our love and you did too",
    "i broke promises and you broke yours",
    "i lied to you and you lied to me",
    "i hurt you and you hurt me",
    "i betrayed us both",
    "i destroyed everything we had",
    "i broke what we could have been"
  ],
  "trust_destroyed": [
    "i can never trust you again",
    "i can never trust anyone again",
    "i can never trust love again",
    "i can never trust myself again",
    "i can never trust the future again",
    "i can never trust happiness again",
    "i can never trust hope again",
    "i can never trust dreams again",
    "i can never trust promises again",
    "i can never trust words again"
  ],
  "betrayal_by_friend": [
    "i thought you were my friend",
    "i trusted you with everything",
    "i never thought you'd betray me",
    "i thought you had my back",
    "i believed in your loyalty",
    "i thought you were different",
    "i never saw the betrayal coming",
    "i thought you were safe",
    "i trusted you completely",
    "i never thought you'd hurt me"
  ],

  // Emptiness subcategories
  "empty_without_you": [
    "you took yourself and left me hollow",
    "emptiness echoes where you used to be",
    "i am a shell of who i was with you",
    "you left and took my wholeness with you",
    "empty rooms remind me of empty hearts"
  ],
  "hollow_inside": [
    "hollowness lives where my heart should be",
    "i am carved out and echoing",
    "hollow is the sound of my name without you",
    "i am empty space pretending to be person",
    "hollowness fills every corner of my being"
  ],
  "void_in_heart": [
    "there's a you-shaped void in my chest",
    "the void grows larger every day",
    "my heart is a black hole where you used to be",
    "void is the only word for this absence",
    "the void consumes everything good"
  ],
  "numb_and_empty": [
    "numbness is my default setting now",
    "i feel nothing which is worse than everything",
    "empty and numb is my natural state",
    "numbness protects me from the emptiness",
    "i am void of feeling void of you"
  ],
  "emptiness_consumes": [
    "emptiness eats me from the inside out",
    "the void grows hungrier each day",
    "emptiness is a living thing inside me",
    "i am being consumed by my own absence",
    "emptiness feeds on what's left of me"
  ],

  // Obsession subcategories
  "cant_stop_thinking": [
    "i can't stop thinking about you",
    "i can't get you out of my mind",
    "i can't stop replaying our memories",
    "i can't stop thinking about us",
    "i can't stop thinking about what we had",
    "i can't stop thinking about what we lost",
    "i can't stop thinking about what we could have been",
    "i can't stop thinking about what we should have been",
    "i can't stop thinking about what we were",
    "i can't stop thinking about what we are"
  ],
  "consumed_by_you": [
    "i'm completely consumed by thoughts of you",
    "i'm totally consumed by memories of you",
    "i'm entirely consumed by love for you",
    "i'm wholly consumed by desire for you",
    "i'm fully consumed by need for you",
    "i'm completely consumed by want for you",
    "i'm totally consumed by longing for you",
    "i'm entirely consumed by missing you",
    "i'm wholly consumed by yearning for you",
    "i'm fully consumed by craving you"
  ],
  "unhealthy_fixation": [
    "i know my fixation on you is unhealthy",
    "i know my obsession with you is toxic",
    "i know my addiction to you is dangerous",
    "i know my need for you is unhealthy",
    "i know my want for you is toxic",
    "i know my desire for you is dangerous",
    "i know my longing for you is unhealthy",
    "i know my craving for you is toxic",
    "i know my yearning for you is dangerous",
    "i know my love for you is unhealthy"
  ],
  "obsessed_with_memories": [
    "i'm obsessed with memories of you",
    "i'm obsessed with memories of us",
    "i'm obsessed with memories of what we had",
    "i'm obsessed with memories of what we lost",
    "i'm obsessed with memories of what we could have been",
    "i'm obsessed with memories of what we should have been",
    "i'm obsessed with memories of what we were",
    "i'm obsessed with memories of what we are",
    "i'm obsessed with memories of what we will be",
    "i'm obsessed with memories of what we won't be"
  ],
  "addicted_to_you": [
    "i'm addicted to thoughts of you",
    "i'm addicted to memories of you",
    "i'm addicted to love for you",
    "i'm addicted to desire for you",
    "i'm addicted to need for you",
    "i'm addicted to want for you",
    "i'm addicted to longing for you",
    "i'm addicted to missing you",
    "i'm addicted to yearning for you",
    "i'm addicted to craving you"
  ],

  // Passion subcategories
  "burning_desire": [
    "i have burning desire for you",
    "i feel burning desire for you",
    "i experience burning desire for you",
    "i live with burning desire for you",
    "i carry burning desire for you",
    "i hold burning desire for you",
    "i keep burning desire for you",
    "i nurture burning desire for you",
    "i feed burning desire for you",
    "i grow burning desire for you"
  ],
  "wild_love": [
    "i feel wild love for you",
    "i experience wild love for you",
    "i live with wild love for you",
    "i carry wild love for you",
    "i hold wild love for you",
    "i keep wild love for you",
    "i nurture wild love for you",
    "i feed wild love for you",
    "i grow wild love for you",
    "i feel wild love for you"
  ],
  "fierce_attraction": [
    "i feel fierce attraction to you",
    "i experience fierce attraction to you",
    "i live with fierce attraction to you",
    "i carry fierce attraction to you",
    "i hold fierce attraction to you",
    "i keep fierce attraction to you",
    "i nurture fierce attraction to you",
    "i feed fierce attraction to you",
    "i grow fierce attraction to you",
    "i feel fierce attraction to you"
  ],
  "passionate_fire": [
    "i feel passionate fire for you",
    "i experience passionate fire for you",
    "i live with passionate fire for you",
    "i carry passionate fire for you",
    "i hold passionate fire for you",
    "i keep passionate fire for you",
    "i nurture passionate fire for you",
    "i feed passionate fire for you",
    "i grow passionate fire for you",
    "i feel passionate fire for you"
  ],
  "intense_connection": [
    "i feel intense connection with you",
    "i experience intense connection with you",
    "i live with intense connection with you",
    "i carry intense connection with you",
    "i hold intense connection with you",
    "i keep intense connection with you",
    "i nurture intense connection with you",
    "i feed intense connection with you",
    "i grow intense connection with you",
    "i feel intense connection with you"
  ],

  // Pride subcategories
  "proud_of_us": [
    "i'm proud of what we built together",
    "i'm proud of the love we shared",
    "i'm proud of the memories we created",
    "i'm proud of the future we planned",
    "i'm proud of the dreams we shared",
    "i'm proud of the life we built",
    "i'm proud of the happiness we knew",
    "i'm proud of the peace we had",
    "i'm proud of the trust we shared",
    "i'm proud of the bond we formed"
  ],
  "too_proud_to_beg": [
    "i'm too proud to beg for your love",
    "i'm too proud to crawl back to you",
    "i'm too proud to ask for forgiveness",
    "i'm too proud to admit i need you",
    "i'm too proud to show my weakness",
    "i'm too proud to admit my mistakes",
    "i'm too proud to ask for help",
    "i'm too proud to show my vulnerability",
    "i'm too proud to admit my pain",
    "i'm too proud to show my heartbreak"
  ],
  "swallowing_pride": [
    "i'm swallowing my pride for you",
    "i'm eating my pride for your love",
    "i'm choking on my pride for you",
    "i'm sacrificing my pride for you",
    "i'm giving up my pride for you",
    "i'm letting go of my pride for you",
    "i'm abandoning my pride for you",
    "i'm destroying my pride for you",
    "i'm killing my pride for you",
    "i'm burying my pride for you"
  ],
  "pride_before_fall": [
    "i think my pride led to our fall",
    "i believe my pride destroyed us",
    "i feel like my pride ruined everything",
    "i think my pride was our downfall",
    "i believe my pride killed our love",
    "i feel like my pride broke our bond",
    "i think my pride destroyed our future",
    "i believe my pride ruined our happiness",
    "i feel like my pride killed our peace",
    "i think my pride destroyed our trust"
  ],
  "damaged_pride": [
    "i feel like you damaged my pride",
    "i think you wounded my pride",
    "i believe you broke my pride",
    "i feel like you destroyed my pride",
    "i think you killed my pride",
    "i believe you ruined my pride",
    "i feel like you shattered my pride",
    "i think you crushed my pride",
    "i believe you annihilated my pride",
    "i feel like you obliterated my pride"
  ],

  // Yearning subcategories
  "yearn_for_touch": [
    "i yearn for your touch constantly",
    "i yearn for your touch desperately",
    "i yearn for your touch endlessly",
    "i yearn for your touch painfully",
    "i yearn for your touch hopelessly",
    "i yearn for your touch completely",
    "i yearn for your touch totally",
    "i yearn for your touch absolutely",
    "i yearn for your touch entirely",
    "i yearn for your touch wholly"
  ],
  "desperate_need": [
    "i have desperate need for you",
    "i feel desperate need for you",
    "i experience desperate need for you",
    "i live with desperate need for you",
    "i carry desperate need for you",
    "i hold desperate need for you",
    "i keep desperate need for you",
    "i nurture desperate need for you",
    "i feed desperate need for you",
    "i grow desperate need for you"
  ],
  "soul_yearning": [
    "i have soul yearning for you",
    "i feel soul yearning for you",
    "i experience soul yearning for you",
    "i live with soul yearning for you",
    "i carry soul yearning for you",
    "i hold soul yearning for you",
    "i keep soul yearning for you",
    "i nurture soul yearning for you",
    "i feed soul yearning for you",
    "i grow soul yearning for you"
  ],
  "yearning_for_past": [
    "i yearn for the past we had",
    "i yearn for the people we were",
    "i yearn for the love we shared",
    "i yearn for the happiness we knew",
    "i yearn for the peace we had",
    "i yearn for the trust we shared",
    "i yearn for the bond we formed",
    "i yearn for the future we planned",
    "i yearn for the dreams we shared",
    "i yearn for the life we built"
  ],
  "unfulfilled_yearning": [
    "i have unfulfilled yearning for you",
    "i feel unfulfilled yearning for you",
    "i experience unfulfilled yearning for you",
    "i live with unfulfilled yearning for you",
    "i carry unfulfilled yearning for you",
    "i hold unfulfilled yearning for you",
    "i keep unfulfilled yearning for you",
    "i nurture unfulfilled yearning for you",
    "i feed unfulfilled yearning for you",
    "i grow unfulfilled yearning for you"
  ]
};
