export const typewriterTags: string[] = [
	"Anger",
	"Apology",
  "Betrayal",
	"Blame",
  "Closure",
	"Confession",
  "Devotion",
  "Emptiness",
  "Fear",
	"Forgiveness",
	"Goodbye",
  "Gratitude",
  "Guilt",
  "Hate",
	"Heartbreak",
  "Hope",
  "Jealousy",
	"Love",
  "Longing",
  "Missing",
  "Nostalgia",
  "Obsession",
  "Passion",
  "Pride",
	"Regret",
	"Sadness",
  "Shame",
  "Thank You",
  "Vulnerability",
  "Yearning",
	"Other"
];

export const typewriterSubTags: Record<string, string[]> = {
  "Anger": ["angry_at_you", "angry_at_myself", "angry_at_situation", "not_angry_anymore"],
  "Apology": ["im_sorry", "you_should_be_sorry", "both_need_apologize", "im_not_sorry"],
  "Betrayal": ["you_betrayed_me", "i_betrayed_you", "mutual_betrayal", "trust_destroyed", "betrayal_by_friend"],
  "Blame": ["blame_you", "blame_myself", "both_to_blame", "no_one_to_blame"],
  "Confession": ["have_to_tell_you", "keep_secret", "i_was_wrong", "you_were_wrong", "both_made_mistakes"],
  "Devotion": ["devoted_to_you", "worship_your_existence", "you_are_my_religion", "unconditional_love", "would_die_for_you"],
  "Emptiness": ["empty_without_you", "hollow_inside", "void_in_heart", "numb_and_empty", "emptiness_consumes"],
  "Fear": ["afraid_losing_you", "afraid_commitment", "afraid_future", "not_afraid_anymore"],
  "Forgiveness": ["asking_forgiveness", "forgive_you", "cant_forgive", "forgive_myself", "need_forgive_each_other"],
  "Goodbye": ["goodbye_forever", "see_you_again", "im_leaving", "dont_leave", "need_part_ways"],
  "Gratitude": ["thank_everything", "thank_lessons", "grateful_us", "grateful_pain"],
  "Guilt": ["feel_guilty", "innocent", "you_should_guilty", "no_one_guilty", "both_guilty"],
  "Hate": ["hate_you", "hate_myself", "hate_what_we_became", "dont_hate_anymore", "i_cant_hate_you"],
  "Heartbreak": ["you_broke_heart", "broke_own_heart", "broke_each_other", "heart_healing"],
  "Hope": ["hope_for_us", "hope_you_return", "hope_for_healing", "hope_is_fading", "never_give_up_hope"],
  "Jealousy": ["jealous_of_you", "jealous_of_others", "you_jealous_of_me", "not_jealous_anymore"],
  "Love": ["love_you", "dont_love_anymore", "love_cant_be_together", "still_love", "never_loved"],
  "Longing": ["ache_for_you", "desperate_yearning", "craving_your_touch", "starving_for_you", "endless_desire"],
  "Missing": ["miss_you", "dont_miss_anymore", "miss_who_you_were", "miss_who_we_were", "miss_myself"],
  "Nostalgia": ["remember_good_times", "miss_our_past", "better_days", "golden_memories", "wish_we_could_go_back"],
  "Obsession": ["cant_stop_thinking", "consumed_by_you", "unhealthy_fixation", "obsessed_with_memories", "addicted_to_you"],
  "Passion": ["burning_desire", "wild_love", "fierce_attraction", "passionate_fire", "intense_connection"],
  "Pride": ["proud_of_us", "too_proud_to_beg", "swallowing_pride", "pride_before_fall", "damaged_pride"],
  "Regret": ["regret_everything", "no_regrets", "regret_not_trying", "regret_meeting", "both_have_regrets"],
  "Sadness": ["so_sad", "finding_happiness", "sad_what_lost", "sad_for_you", "sad_for_me"],
  "Shame": ["ashamed", "proud_myself", "you_should_ashamed", "both_should_ashamed", "no_one_ashamed"],
  "Thank You": ["thank_you", "no_thanks_needed", "thank_pain", "thank_memories", "thank_leaving"],
  "Vulnerability": ["opening_my_heart", "showing_weakness", "need_protection", "trust_you_completely", "exposed_and_fragile"],
  "Yearning": ["yearn_for_touch", "desperate_need", "soul_yearning", "yearning_for_past", "unfulfilled_yearning"],
  "Closure": ["need_answers", "dont_need_answers", "need_understand", "need_move_on", "need_closure", "never_got_closure", "seeking_closure", "closure_impossible", "found_own_closure"],
  "Other": ["other_feeling", "different_emotion", "something_else", "cant_explain", "complicated"]
};

export const typewriterPromptsBySubTag: Record<string, string[]> = {
  // Anger subcategories
  "angry_at_you": [
    "your name tastes like poison on my tongue",
    "i wake up furious that you still breathe easy",
    "every happy memory of you now feels like a slap",
    "i'm drowning in rage while you sleep peacefully",
    "you stole my peace and left me with this fire",
    "your face haunts me like a crime scene i can't leave",
    "i want to scream your name until my voice breaks",
    "you ruined the person i was and walked away smiling",
    "my anger at you is the only thing keeping me alive",
    "you broke me and i hate that part of me still wants you"
  ],
  "angry_at_myself": [
    "i gave you pieces of me i can never get back",
    "i hate that i still check if you've called",
    "i ignored every red flag like they were love notes",
    "i'm furious i wasted years on someone so careless",
    "i hate how small i made myself to fit your world",
    "i gave you my heart and you treated it like trash",
    "i'm angry i let you convince me i was the problem",
    "i hate that i still defend you to people who saw the truth",
    "i ignored my gut feeling and now i'm paying for it",
    "i'm furious at the person i became just to keep you"
  ],
  "angry_at_situation": [
    "we had everything and life took it away for nothing",
    "the timing was perfect until it wasn't",
    "i'm furious we loved each other at the wrong time",
    "fate gave us to each other then ripped us apart",
    "i'm angry the universe let us meet just to suffer",
    "we deserved better than the hand we were dealt",
    "i'm raging at a world that let us fall in love and fail",
    "life promised us forever then pulled the rug out",
    "i hate that loving you was right and wrong at once",
    "the cruelest joke is that we could've worked anywhere else"
  ],
  "not_angry_anymore": [
    "the anger faded and left me with nothing",
    "i'm too exhausted to hate you anymore",
    "rage turned to ash and i'm just empty now",
    "i don't have the energy to be mad at you",
    "my anger died and took my hope with it",
    "i'm too numb to feel fury anymore",
    "the rage burned out and left me hollow",
    "i'm past anger now, just quietly broken",
    "fury turned to fog and i can't feel anything",
    "i'm too tired to even remember why i was mad"
  ],

  // Apology subcategories
  "im_sorry": [
    "i'm sorry i wasn't what you needed me to be",
    "i'm sorry for every time i made you feel alone",
    "i'm sorry i loved you so much it suffocated us",
    "i'm sorry i stayed when leaving would've saved us both",
    "i'm sorry for all the words i should've said sooner",
    "i'm sorry i couldn't be strong enough for both of us",
    "i'm sorry i let my insecurities poison what we had",
    "i'm sorry for every promise i couldn't keep",
    "i'm sorry i made you the villain in my head",
    "i'm sorry i couldn't let you go when you needed to leave"
  ],
  "you_should_be_sorry": [
    "you owe me an apology for treating me like i was replaceable",
    "you should be sorry for making me feel crazy",
    "you need to apologize for the years i wasted waiting",
    "you owe me sorry for every lie i believed",
    "you should be sorry for making promises you knew you'd break",
    "you need to apologize for using my love against me",
    "you owe me sorry for leaving without a real goodbye",
    "you should be sorry for making me doubt my worth",
    "you need to apologize for the person you made me become",
    "you owe me sorry for walking away like i meant nothing"
  ],
  "both_need_apologize": [
    "we both broke each other in ways we can't take back",
    "i'm sorry for my part and i know you hurt too",
    "we both said things we can't unsay",
    "i'm sorry for the damage i caused and the damage you left",
    "we both failed at loving each other right",
    "i'm sorry i wasn't perfect and you weren't either",
    "we both hurt each other trying not to get hurt",
    "i'm sorry for my mistakes and yours still sting",
    "we both needed to be better than we were",
    "i'm sorry we couldn't save each other or ourselves"
  ],
  "im_not_sorry": [
    "i'm not sorry for finally choosing my own peace",
    "i'm not sorry for leaving when staying was killing me",
    "i'm not sorry for protecting what was left of my heart",
    "i'm not sorry for refusing to be your second choice",
    "i'm not sorry for walking away from someone who didn't fight for me",
    "i'm not sorry for finally loving myself more than you",
    "i'm not sorry for setting boundaries you called selfish",
    "i'm not sorry for choosing the life you said i couldn't have",
    "i'm not sorry for healing in ways that didn't include you",
    "i'm not sorry for becoming someone you no longer recognize"
  ],

  // Blame subcategories
  "blame_you": [
    "you made me believe i was too much and not enough",
    "you turned my love into something i'm ashamed of",
    "you took the best parts of me and left me with scraps",
    "you made me question if i was ever worth loving",
    "you broke me in ways i didn't know were possible",
    "you taught me that trust is just another word for stupid",
    "you made me feel like loving you was my biggest mistake",
    "you turned every memory we had into something that hurts",
    "you stole my ability to love without fear",
    "you made me hate the person i became while loving you"
  ],
  "blame_myself": [
    "i blame myself for ignoring who you really were",
    "i blame myself for believing love would be enough",
    "i blame myself for staying long after i should've left",
    "i blame myself for giving you power to destroy me",
    "i blame myself for making excuses for your behavior",
    "i blame myself for losing who i was trying to keep you",
    "i blame myself for thinking i could change you",
    "i blame myself for every time i chose you over me",
    "i blame myself for letting you convince me i was the problem",
    "i blame myself for wasting years on someone who didn't care"
  ],
  "both_to_blame": [
    "we both destroyed what could've been beautiful",
    "we both chose pride over trying to understand each other",
    "we both said hurtful things we can never take back",
    "we both stopped fighting for us at different times",
    "we both let our fears turn love into a battlefield",
    "we both broke promises we swore we'd keep",
    "we both hurt each other more than outsiders ever could",
    "we both gave up instead of growing up together",
    "we both turned love into something unrecognizable",
    "we both knew it was ending but neither stopped it"
  ],
  "no_one_to_blame": [
    "sometimes love just isn't enough and that's nobody's fault",
    "we tried our best and it still wasn't meant to be",
    "timing can kill even the strongest love",
    "we loved each other wrong but not on purpose",
    "sometimes people just aren't meant to last",
    "we outgrew each other and that's just life",
    "loving each other and being right for each other aren't the same",
    "we were both doing our best with broken pieces",
    "sometimes goodbye is no one's fault",
    "we just weren't meant to be forever and that's okay"
  ],

  // Confession subcategories
  "have_to_tell_you": [
    "i need to confess that i still dream about you every night",
    "i have to tell you that leaving you was the hardest thing i've done",
    "i need to confess that i think about you in every love song",
    "i have to tell you that i'm still in love with who you used to be",
    "i need to confess that i check your social media even though it hurts",
    "i have to tell you that i've never loved anyone the way i loved you",
    "i need to confess that i still wear the shirt you left behind",
    "i have to tell you that i saved all our messages and read them when i'm weak",
    "i need to confess that i'm not over you and i don't know if i ever will be",
    "i have to tell you that you're still the first person i want to call with good news"
  ],
  "keep_secret": [
    "i'll never tell you how many times i've driven past your house",
    "i'll keep it secret that i still have your number memorized",
    "i'll never admit that i compare everyone to you",
    "i'll keep it secret that i cry on our anniversary every year",
    "i'll never tell you that i kept every gift you gave me",
    "i'll keep it secret that i still sleep on my side of the bed",
    "i'll never admit that i pray you'll come back someday",
    "i'll keep it secret that i've never deleted our photos",
    "i'll never tell you that i still love you more than i should",
    "i'll keep it secret that you're the reason i'm afraid to love again"
  ],
  "i_was_wrong": [
    "i was wrong to think we could fix everything with love",
    "i was wrong to ignore the signs that we were falling apart",
    "i was wrong to believe you when you said you'd never leave",
    "i was wrong to think i could be enough for you",
    "i was wrong to stay when every bone in my body said go",
    "i was wrong to make you my whole world instead of just part of it",
    "i was wrong to think loving harder would make you love me back",
    "i was wrong to believe time would heal what we broke",
    "i was wrong to think we'd be different from everyone else",
    "i was wrong to give you chances you never asked for"
  ],
  "you_were_wrong": [
    "you were wrong to think i'd wait forever",
    "you were wrong to treat my love like it was guaranteed",
    "you were wrong to believe i'd always be there after you left",
    "you were wrong to think i wouldn't find someone better",
    "you were wrong to underestimate how much i could love myself",
    "you were wrong to think i needed you to be whole",
    "you were wrong to believe i'd never move on",
    "you were wrong to take my loyalty for granted",
    "you were wrong to think i'd keep breaking for you",
    "you were wrong to assume i'd always be your backup plan"
  ],
  "both_made_mistakes": [
    "we both thought love would be enough to save us",
    "we both held grudges instead of having hard conversations",
    "we both expected the other to read our minds",
    "we both kept score instead of being on the same team",
    "we both let pride stand in the way of apologizing",
    "we both chose to be right over being happy",
    "we both stopped trying when things got hard",
    "we both made promises we knew we couldn't keep",
    "we both hurt each other when we were hurting ourselves",
    "we both gave up on us at different times"
  ],

  // Fear subcategories
  "afraid_losing_you": [
    "i'm terrified you'll leave and i'll never recover",
    "i'm scared that one day you'll wake up and not love me anymore",
    "i'm afraid i'm not enough to make you stay",
    "i'm terrified of the silence after you're gone",
    "i'm scared you'll forget me faster than i can forget you",
    "i'm afraid of becoming a stranger to the person who knew me best",
    "i'm terrified you'll find someone who loves you better than i could",
    "i'm scared that losing you means losing myself",
    "i'm afraid you'll realize you never needed me at all",
    "i'm terrified that you're already one foot out the door"
  ],
  "afraid_commitment": [
    "i'm scared that forever is just another word for trapped",
    "i'm terrified of losing myself trying to be what you need",
    "i'm afraid commitment means giving up who i am",
    "i'm scared that loving you will mean losing my freedom",
    "i'm terrified of becoming someone i don't recognize for you",
    "i'm afraid that staying means settling for less than i deserve",
    "i'm scared commitment will turn our love into obligation",
    "i'm terrified of waking up one day and resenting you",
    "i'm afraid of choosing you and regretting it later",
    "i'm scared that forever with you means never with anyone else"
  ],
  "afraid_future": [
    "i'm terrified we'll outgrow each other",
    "i'm scared tomorrow will prove we were never meant to last",
    "i'm afraid the future will show us we made a mistake",
    "i'm terrified time will reveal we're not compatible",
    "i'm scared we'll become another story that didn't work out",
    "i'm afraid of investing years just to lose you anyway",
    "i'm terrified of building a life together that crumbles",
    "i'm scared the person you become won't love the person i am",
    "i'm afraid we're loving each other on borrowed time",
    "i'm terrified the future we dream about will never come"
  ],
  "not_afraid_anymore": [
    "i'm not afraid of being alone because i found myself again",
    "i'm not scared of starting over without you",
    "i'm not afraid of the future because i'm finally in control",
    "i'm not scared of losing you because i already survived it",
    "i'm not afraid of the unknown anymore, it's better than this pain",
    "i'm not scared of walking away from something that's killing me",
    "i'm not afraid of the silence because it's better than fighting",
    "i'm not scared of life without you, i'm excited for it",
    "i'm not afraid of being hurt again because i'm stronger now",
    "i'm not scared anymore because the worst already happened"
  ],

  // Forgiveness subcategories
  "asking_forgiveness": [
    "i'm begging you to forgive the person i became when i was hurting",
    "i need your forgiveness even though i don't deserve it",
    "i'm asking you to forgive me for not being brave enough to stay",
    "i need you to forgive the words i can't take back",
    "i'm pleading for forgiveness for the nights i made you cry",
    "i need you to forgive me for breaking promises i meant to keep",
    "i'm asking for grace for all the ways i failed you",
    "i need your forgiveness so i can finally forgive myself",
    "i'm begging you to forgive the damage i caused",
    "i need you to forgive me for leaving when you needed me most"
  ],
  "forgive_you": [
    "i forgive you even though it still hurts to breathe",
    "i forgive you for choosing someone else over me",
    "i forgive you for the promises you broke so easily",
    "i forgive you for making me feel like i was never enough",
    "i forgive you for leaving without fighting for us",
    "i forgive you for the lies that rewrote our entire story",
    "i forgive you for the future you stole from me",
    "i forgive you for making me doubt if i was ever loved",
    "i forgive you for walking away like i was nothing",
    "i forgive you not because you deserve it but because i need peace"
  ],
  "cant_forgive": [
    "i can't forgive how easily you replaced me",
    "i can't forgive the way you made me beg for basic decency",
    "i can't forgive that you knew you were breaking me and didn't stop",
    "i can't forgive the years you wasted pretending",
    "i can't forgive how you made me feel crazy for trusting my gut",
    "i can't forgive that you let me plan a future you never wanted",
    "i can't forgive the version of me that died loving you",
    "i can't forgive that you're fine while i'm still broken",
    "i can't forgive the lies you're still telling about us",
    "i can't forgive that you walked away without looking back"
  ],
  "forgive_myself": [
    "i need to forgive myself for loving someone who didn't love me back",
    "i'm trying to forgive myself for ignoring all the red flags",
    "i want to forgive myself for staying longer than i should have",
    "i need to forgive myself for believing someone who kept lying",
    "i'm learning to forgive myself for the years i lost",
    "i want to forgive myself for making you my entire world",
    "i need to forgive myself for not choosing me first",
    "i'm working on forgiving myself for the person i became",
    "i want to forgive myself for thinking love was enough",
    "i need to forgive myself for not leaving when i knew i should"
  ],
  "need_forgive_each_other": [
    "we both need to forgive each other for the war we waged",
    "we both need to let go of who hurt who first",
    "we both need to forgive the damage we did to each other",
    "we both need to accept we loved each other wrong",
    "we both need to forgive ourselves for not being enough",
    "we both need to stop replaying who was right and who was wrong",
    "we both need to forgive the dreams that died between us",
    "we both need to accept we failed at forever",
    "we both need to forgive each other so we can finally move on",
    "we both need to let go of the people we were together"
  ],

  // Goodbye subcategories
  "goodbye_forever": [
    "this is the last time i'll ever say your name out loud",
    "i'm closing the door on us and i won't look back",
    "goodbye to the future we'll never have",
    "this is me choosing myself for the first time",
    "i'm saying goodbye to someone who stopped fighting for me",
    "this is the final time i'll cry over you",
    "goodbye to the version of me that believed you'd change",
    "i'm done waiting for you to choose me",
    "this is me letting go of what we could've been",
    "goodbye to the person who made me feel like i wasn't enough"
  ],
  "see_you_again": [
    "maybe in another life we'll get the timing right",
    "i hope we meet again when we're both healed",
    "maybe someday we'll be strangers who once loved deeply",
    "i'll see you in memories i'm not ready to let go of yet",
    "maybe in another timeline we work out",
    "i hope our paths cross when we're better versions of ourselves",
    "maybe we'll laugh about this pain someday",
    "i'll see you in the what-ifs that haunt me",
    "maybe fate will bring us back when we're ready",
    "i hope you remember me fondly when you think of us"
  ],
  "im_leaving": [
    "i'm leaving because staying is killing me slowly",
    "i'm walking away from the person who forgot my worth",
    "i'm leaving the cage i built around my heart for you",
    "i'm done fighting for someone who won't fight for me",
    "i'm leaving before there's nothing left of me to save",
    "i'm walking away from love that hurts more than heals",
    "i'm leaving the version of me that begged for your attention",
    "i'm done sacrificing my peace for your comfort",
    "i'm leaving this toxicity disguised as love",
    "i'm walking away from someone who made me feel small"
  ],
  "dont_leave": [
    "please don't leave, i'm still learning how to love you right",
    "i'm begging you to stay and fight for us one more time",
    "please don't go, i can't survive losing you",
    "stay, please, i'll be better i swear",
    "don't leave me here drowning in the silence",
    "i'm not ready to let you become a memory",
    "please stay, i'll change everything you hate about me",
    "don't go, i don't know who i am without you",
    "please give us one more chance to get it right",
    "stay, because losing you will break me beyond repair"
  ],
  "need_part_ways": [
    "i need to leave so we can both find ourselves again",
    "we need to part ways before we destroy each other completely",
    "i need to walk away before i lose myself entirely",
    "we need to say goodbye so we can both start healing",
    "i need to let you go even though it's tearing me apart",
    "we need to separate before our love turns to hate",
    "i need to leave because loving you is costing me myself",
    "we need to part ways before there's nothing left to save",
    "i need to walk away to remember who i was before you",
    "we need to end this before we both become unrecognizable"
  ],

  // Gratitude subcategories
  "thank_everything": [
    "thank you for loving me even if it wasn't forever",
    "i'm grateful for every moment even the ones that hurt",
    "thank you for showing me what love could feel like",
    "i'm grateful we had what we had while it lasted",
    "thank you for the memories i'll carry forever",
    "i'm grateful you were mine even if just for a while",
    "thank you for teaching me how to love deeply",
    "i'm grateful for the dreams we shared even if they died",
    "thank you for the laughter before the tears",
    "i'm grateful our paths crossed even if they had to part"
  ],
  "thank_lessons": [
    "thank you for teaching me what i deserve and what i don't",
    "i'm grateful you showed me my own strength",
    "thank you for the lessons that hurt but made me wiser",
    "i'm grateful you taught me how to let go",
    "thank you for showing me what love shouldn't look like",
    "i'm grateful you forced me to choose myself",
    "thank you for the pain that led to growth",
    "i'm grateful you taught me i can survive anything",
    "thank you for showing me i'm stronger than i thought",
    "i'm grateful for the truth even though it broke me"
  ],
  "grateful_us": [
    "i'm grateful we tried even though we failed",
    "thank you for being my person even if not forever",
    "i'm grateful for the love we built even though it crumbled",
    "thank you for making me believe in us",
    "i'm grateful for the version of us that felt invincible",
    "thank you for the future we planned even if it never came",
    "i'm grateful we loved each other the best we could",
    "thank you for the team we were before we fell apart",
    "i'm grateful for what we had before it turned to pain",
    "thank you for loving me in the only way you knew how"
  ],
  "grateful_pain": [
    "i'm grateful for the heartbreak that taught me my worth",
    "thank you for the pain that forced me to heal",
    "i'm grateful for the tears that washed away my illusions",
    "thank you for breaking me so i could rebuild myself stronger",
    "i'm grateful for the suffering that revealed who i really am",
    "thank you for the emptiness that taught me to fill myself",
    "i'm grateful for the loneliness that made me whole",
    "thank you for the darkness that showed me my own light",
    "i'm grateful for the wounds that became my armor",
    "thank you for leaving because it taught me i don't need you"
  ],

  // Guilt subcategories
  "feel_guilty": [
    "i feel guilty for every time i made you feel alone",
    "i carry guilt for not loving you the way you deserved",
    "i feel guilty for staying when i knew it was over",
    "i'm drowning in guilt for the person i became with you",
    "i feel guilty for not fighting harder when it mattered",
    "i carry this guilt for choosing myself over us",
    "i feel guilty for the words i can never unsay",
    "i'm suffocating under the guilt of not being enough",
    "i feel guilty that i'm relieved you're gone",
    "i carry guilt for wasting years we can't get back"
  ],
  "innocent": [
    "i know i'm not to blame for your inability to love me",
    "i did nothing wrong by expecting basic respect",
    "i'm innocent in needing love you couldn't give",
    "i know i'm not responsible for your choices",
    "i did nothing wrong by having standards",
    "i'm innocent in wanting what i deserved",
    "i know i'm not the problem, your treatment was",
    "i did nothing wrong by leaving when you hurt me",
    "i'm innocent in expecting you to keep your promises",
    "i know i'm not to blame for your failures"
  ],
  "you_should_guilty": [
    "you should feel guilty for making me question my worth",
    "you should be ashamed of how you treated someone who loved you",
    "you should feel guilty for every lie you made me believe",
    "you should be ashamed of using my love against me",
    "you should feel guilty for the years you wasted leading me on",
    "you should be ashamed of how easily you replaced me",
    "you should feel guilty for breaking promises like they meant nothing",
    "you should be ashamed of the person you made me become",
    "you should feel guilty for leaving without a real explanation",
    "you should be ashamed of how little you fought for us"
  ],
  "no_one_guilty": [
    "nobody's guilty when two people just aren't right for each other",
    "there's no blame when love just isn't enough",
    "nobody's at fault when timing tears people apart",
    "there's no guilt in outgrowing someone",
    "nobody's responsible when two people want different things",
    "there's no blame in loving someone you can't be with",
    "nobody's guilty when life gets in the way",
    "there's no fault in trying and failing",
    "nobody's to blame when love fades naturally",
    "there's no guilt in choosing yourself"
  ],
  "both_guilty": [
    "we're both guilty of holding on longer than we should have",
    "we both share blame for the toxic cycle we created",
    "we're both guilty of choosing pride over love",
    "we both carry fault for the damage we did",
    "we're both guilty of saying things we can't take back",
    "we both share blame for not communicating honestly",
    "we're both guilty of hurting each other on purpose",
    "we both carry fault for letting it get this bad",
    "we're both guilty of giving up instead of growing",
    "we both share blame for destroying something beautiful"
  ],

  // Hate subcategories
  "hate_you": [
    "i hate you for making me feel like i was never enough",
    "i hate you for breaking me and acting like you didn't",
    "i hate you for leaving me when you promised forever",
    "i hate you for every lie disguised as love",
    "i hate you for the person you made me become",
    "i hate you for using my love as a weapon against me",
    "i hate you for the future you stole from me",
    "i hate you for making me doubt everything i thought was real",
    "i hate you for how easily you moved on",
    "i hate you for destroying my ability to trust"
  ],
  "hate_myself": [
    "i hate myself for loving someone who didn't deserve it",
    "i hate myself for seeing red flags and calling them petals",
    "i hate myself for believing your lies for so long",
    "i hate myself for giving you so many chances",
    "i hate myself for sacrificing who i was for who you wanted",
    "i hate myself for defending you to people who saw the truth",
    "i hate myself for making you my whole world",
    "i hate myself for thinking i could fix you",
    "i hate myself for staying when my gut screamed leave",
    "i hate myself for the years i'll never get back"
  ],
  "hate_what_we_became": [
    "i hate that we turned love into a battlefield",
    "i hate how toxic we became trying to make it work",
    "i hate that we destroyed the beauty we once had",
    "i hate how we became each other's worst enemy",
    "i hate that our love story ended in resentment",
    "i hate the strangers we became to each other",
    "i hate that we let it get so broken",
    "i hate how we poisoned something that started pure",
    "i hate that we couldn't save us from ourselves",
    "i hate that we're now just a cautionary tale"
  ],
  "dont_hate_anymore": [
    "i don't hate you anymore, i'm just indifferent now",
    "i'm too tired to hate you, the anger finally died",
    "i don't have energy for hate, it's been replaced with nothing",
    "i'm done hating you because it was hurting me more",
    "i don't feel hate anymore, just sad for what we were",
    "i'm too empty to hate, you took that feeling too",
    "i don't hate you anymore, you're just a stranger now",
    "i'm too numb to hate, i barely feel anything",
    "i don't hate you anymore, i pity us both",
    "i'm past hate now, it's just acceptance and exhaustion"
  ],
  "i_cant_hate_you": [
    "i can't hate you even though you deserve it",
    "i want to hate you but love won't let me",
    "i try to hate you but memories stop me",
    "i wish i could hate you, it would hurt less",
    "i should hate you but i still care too much",
    "i want to hate you so moving on would be easier",
    "i need to hate you to stop missing you",
    "i want to hate you but i remember who you were",
    "i should hate you for what you did but i can't",
    "i want to hate you to heal but my heart won't cooperate"
  ],

  // Heartbreak subcategories
  "you_broke_heart": [
    "you broke my heart and acted like it was nothing",
    "you shattered every piece of me i gave you",
    "you destroyed the part of me that believed in forever",
    "you killed the hope i had for us",
    "you broke me in ways i'm still discovering",
    "you crushed every dream i built around you",
    "you stole the future i saw so clearly",
    "you took my happiness like it was yours to take",
    "you destroyed the peace i had before you",
    "you broke me and i don't know how to fix it"
  ],
  "broke_own_heart": [
    "i broke my own heart by loving you too much",
    "i destroyed myself trying to keep you",
    "i killed my own hope by holding on too long",
    "i broke my own spirit staying when i should've left",
    "i crushed my own dreams making you my world",
    "i stole my own future by investing it in you",
    "i took my own happiness and gave it away to you",
    "i destroyed my own peace trying to fix us",
    "i broke everything i had trying to save us",
    "i ruined myself believing you'd change"
  ],
  "broke_each_other": [
    "we broke each other trying to make broken work",
    "we destroyed each other's ability to love freely",
    "we killed each other's hope one fight at a time",
    "we broke each other's spirits with every lie",
    "we crushed each other's dreams in the wreckage",
    "we stole each other's futures trying to hold on",
    "we took each other's happiness and buried it",
    "we destroyed each other's peace in the chaos",
    "we broke everything beautiful we once had",
    "we ruined each other trying to save ourselves"
  ],
  "heart_healing": [
    "my heart is slowly learning to beat without you",
    "i'm getting better at existing in the silence",
    "i'm starting to heal even though it's painful",
    "my heart is mending itself one day at a time",
    "i'm finding peace in the wreckage you left",
    "i'm moving forward even though i look back",
    "my heart is growing stronger from the breaking",
    "i'm learning to love myself after you couldn't",
    "i'm finding hope in places you never looked",
    "my heart is beating again, just not for you"
  ],

  // Jealousy subcategories
  "jealous_of_you": [
    "i'm jealous you moved on while i'm still stuck",
    "i'm jealous you found peace while i'm still drowning",
    "i'm jealous of the new life you built without me",
    "i'm jealous you can forget us so easily",
    "i'm jealous you found happiness i never gave you",
    "i'm jealous you're thriving while i'm barely surviving",
    "i'm jealous you escaped us unscathed",
    "i'm jealous you got the future i wanted for us",
    "i'm jealous you can love again and i'm still broken",
    "i'm jealous you're free while i'm still trapped in memories"
  ],
  "jealous_of_others": [
    "i'm jealous of couples who don't know what it's like to break",
    "i'm jealous of people who've never felt this kind of pain",
    "i'm jealous of those who can trust without fear",
    "i'm jealous of people who found their forever",
    "i'm jealous of those who don't understand this emptiness",
    "i'm jealous of people who can love without trauma",
    "i'm jealous of couples who make it look easy",
    "i'm jealous of those who've never been broken like this",
    "i'm jealous of people who still believe in happy endings",
    "i'm jealous of those who have what we couldn't keep"
  ],
  "you_jealous_of_me": [
    "you're jealous i'm thriving without you",
    "you're jealous i chose myself over staying broken",
    "you're jealous i found peace you never gave me",
    "you're jealous i built a life you're not part of",
    "you're jealous i'm happy in ways you never made me",
    "you're jealous i don't need you anymore",
    "you're jealous i healed from what you did",
    "you're jealous i'm everything you said i couldn't be",
    "you're jealous someone loves me better than you did",
    "you're jealous i moved on and you're stuck"
  ],
  "not_jealous_anymore": [
    "i'm not jealous anymore because i found my own happiness",
    "i don't feel jealousy because i'm content with my journey",
    "i'm over being jealous because i learned to love myself",
    "i don't care what others have because i have enough",
    "i'm content with where i am in life now",
    "i don't compare myself because my path is mine alone",
    "i'm happy with what i've built for myself",
    "i don't want what others have because mine is enough",
    "i'm grateful for my own story and growth",
    "i don't feel envy because i'm finally at peace"
  ],

  // Love subcategories
  "love_you": [
    "i love you in a way that terrifies me",
    "i love you with every broken piece of me",
    "i love you more than i love myself and that's the problem",
    "i love you in ways that hurt to feel",
    "i love you with everything i have left to give",
    "i love you so much it's destroying me",
    "i love you in a way i'll never love again",
    "i love you more than you'll ever understand",
    "i love you even when you don't love yourself",
    "i love you and it's the most painful thing i've ever felt"
  ],
  "dont_love_anymore": [
    "i don't love you anymore and it scares me how numb i feel",
    "i don't love you the way i used to and it's a relief",
    "i don't feel love for you, just echoes of who we were",
    "i don't love you anymore, i don't even recognize you",
    "i don't love you and i don't know when it stopped",
    "i don't feel anything for you except exhaustion",
    "i don't love you anymore, i'm just tired",
    "i don't love you like before, i barely remember how",
    "i don't love you anymore and i'm not sorry",
    "i don't love you and it's the first time i've felt free"
  ],
  "love_cant_be_together": [
    "i love you but loving you is killing me",
    "i love you but it's not enough to fix us",
    "i love you but we're destroying each other",
    "i love you but staying together is toxic",
    "i love you but we want different futures",
    "i love you but love isn't enough to make this work",
    "i love you but we're hurting more than healing",
    "i love you but we're better apart than together",
    "i love you but the timing will never be right",
    "i love you but we've broken each other beyond repair"
  ],
  "still_love": [
    "i still love you and it's the cruelest joke",
    "i still love you even though you broke me",
    "i still love you after everything you did",
    "i still love you despite knowing i shouldn't",
    "i still love you and i hate myself for it",
    "i still love you even though you're with someone else",
    "i still love you despite all the pain you caused",
    "i still love you and it won't let me move on",
    "i still love you even though you stopped loving me",
    "i still love you and it's my biggest weakness"
  ],
  "never_loved": [
    "i never loved you, i loved the idea of you",
    "i never truly loved you, i was in love with potential",
    "i never loved you, i loved who i thought you were",
    "i never loved you, i loved the attention",
    "i never truly loved you, i was scared to be alone",
    "i never loved you, i loved the version you pretended to be",
    "i never loved you, i was trauma bonded to you",
    "i never truly loved you, i just didn't want to be lonely",
    "i never loved you, i confused need for love",
    "i never loved you, i loved the fantasy we created"
  ],

  // Missing subcategories
  "miss_you": [
    "i miss you in ways that make it hard to breathe",
    "i miss you at 3am when the silence screams your name",
    "i miss you in every song that reminds me of us",
    "i miss you in the mundane moments we used to share",
    "i miss you when i have good news and you're not the first call",
    "i miss you in the empty space beside me",
    "i miss you in ways i didn't know were possible",
    "i miss you every time i see couples that look happy",
    "i miss you in the routines we built together",
    "i miss you like an amputee misses a limb"
  ],
  "dont_miss_anymore": [
    "i don't miss you anymore and it's both freeing and terrifying",
    "i don't miss you like i used to, just the idea of you",
    "i don't miss you at all, i miss who i thought you were",
    "i'm over missing you, it wasn't getting me anywhere",
    "i'm done missing someone who doesn't miss me back",
    "i don't feel the ache of missing you anymore",
    "i don't think about missing you, i think about healing",
    "i don't care about missing you, i care about moving forward",
    "i don't want to miss you anymore, it's exhausting",
    "i don't need to miss you to remember what we had"
  ],
  "miss_who_you_were": [
    "i miss the person you were before you became a stranger",
    "i miss the version of you that actually cared",
    "i miss who you were before the lies took over",
    "i miss the person you pretended to be at the start",
    "i miss the you that existed only in my imagination",
    "i miss the you i thought i knew before reality hit",
    "i miss the you i fell for before you showed your true colors",
    "i miss the you who made promises you meant to keep",
    "i miss the you i believed existed before i saw the truth",
    "i miss the you that never actually existed outside my hopes"
  ],
  "miss_who_we_were": [
    "i miss when we were each other's safe place",
    "i miss the us that laughed more than we fought",
    "i miss when being together felt easy and natural",
    "i miss when we were a team instead of enemies",
    "i miss the us that believed we'd make it",
    "i miss when loving you didn't hurt this much",
    "i miss the future we planned before it crumbled",
    "i miss when we actually liked each other",
    "i miss the us that existed before everything fell apart",
    "i miss when being together felt like coming home"
  ],
  "miss_myself": [
    "i miss the person i was before you broke me",
    "i miss the me that didn't need validation to feel worthy",
    "i miss who i was before i made you my whole world",
    "i miss my old self who was happy and independent",
    "i miss the person i lost trying to keep you",
    "i miss the me that was confident before you tore me down",
    "i miss the me that existed before this heartbreak",
    "i miss the version of me that believed in love",
    "i miss the me that didn't cry themselves to sleep",
    "i miss who i was before loving you changed me"
  ],

  // Regret subcategories
  "regret_everything": [
    "i regret every second i wasted believing in us",
    "i regret every choice that led me to you",
    "i regret every word i should've kept to myself",
    "i regret every moment i prioritized you over me",
    "i regret every memory that now just causes pain",
    "i regret every dream i built around someone so temporary",
    "i regret every plan that had your name in it",
    "i regret every hope i placed in someone who'd leave",
    "i regret loving you more than i loved myself",
    "i regret everything except finally leaving"
  ],
  "no_regrets": [
    "i don't regret us because it taught me what i deserve",
    "i don't regret loving you even though it hurt",
    "i don't regret the pain because it made me stronger",
    "i don't regret us because it showed me who i don't want",
    "i don't regret any moment because it led me here",
    "i don't regret the heartbreak because it set me free",
    "i don't regret loving you because it taught me to love myself",
    "i don't regret the years because they made me who i am",
    "i don't regret us because the lessons were worth the pain",
    "i don't regret anything because regret won't change it"
  ],
  "regret_not_trying": [
    "i regret not fighting harder when we still had a chance",
    "i regret giving up when things got difficult",
    "i regret not communicating when silence built walls",
    "i regret not fighting for us when you stopped trying",
    "i regret letting pride destroy what we could've saved",
    "i regret not being vulnerable when you needed me",
    "i regret walking away instead of working it out",
    "i regret not trying harder to understand you",
    "i regret giving up on us before we gave it our all",
    "i regret not fighting for the love we once had"
  ],
  "regret_meeting": [
    "i regret the day our paths crossed",
    "i regret ever letting you into my life",
    "i regret the moment i gave you my heart",
    "i regret trusting you with my vulnerability",
    "i regret the day i fell for your lies",
    "i regret believing you were different",
    "i regret the moment i chose you over myself",
    "i regret opening my heart to someone who'd break it",
    "i regret every yes i should've made a no",
    "i regret meeting you because now i know this pain"
  ],
  "both_have_regrets": [
    "i think we both have regrets",
    "i believe we both made mistakes",
    "i feel like we both failed each other",
    "i think we both have things we'd change",
    "i believe we both have things we'd do differently",
    "i feel like we both have things we'd undo",
    "i think we both have things we'd redo",
    "i believe we both have things we'd fix",
    "i feel like we both have things we'd improve",
    "i think we both have things we'd correct"
  ],

  // Sadness subcategories
  "so_sad": [
    "i'm so sad it physically hurts to exist",
    "sadness is my permanent state of being now",
    "i'm drowning in sadness that has no end",
    "i carry sadness heavier than my own body",
    "sadness colors every moment without you",
    "i'm so sad i forget what joy felt like",
    "sadness lives in my chest where hope used to be",
    "i'm too sad to pretend i'm okay anymore",
    "sadness is the only emotion i remember how to feel",
    "i'm so sad even my tears have given up"
  ],
  "finding_happiness": [
    "i'm learning to be happy without you",
    "happiness feels foreign after so much pain",
    "i'm finding joy in small things again",
    "i'm slowly remembering what smiling feels like",
    "happiness comes in whispers now not shouts",
    "i'm building a life where happiness is possible",
    "i'm choosing to be happy despite the scars",
    "happiness is work but i'm willing to do it",
    "i'm finding pieces of joy i thought were lost",
    "i'm learning that happiness doesn't require you"
  ],
  "sad_what_lost": [
    "i'm sad we'll never get to grow old together",
    "i'm sad about the future that died with us",
    "i'm sad we'll never make the memories we planned",
    "i'm sad about the life we almost had",
    "i'm sad our story ended before it really began",
    "i'm sad about all the could-have-beens",
    "i'm sad we became strangers who knew everything",
    "i'm sad we lost the magic we once had",
    "i'm sad about the dreams we buried together",
    "i'm sad we couldn't save what we built"
  ],
  "sad_for_you": [
    "i'm sad you'll never know how much you lost",
    "i'm sad you chose temporary over forever",
    "i'm sad you'll realize too late what we had",
    "i'm sad you're living a lie instead of our truth",
    "i'm sad you'll never be truly happy without growth",
    "i'm sad you're missing out on real love",
    "i'm sad you settled for less than we could've been",
    "i'm sad you'll always wonder what if",
    "i'm sad you destroyed something beautiful",
    "i'm sad you'll never find what we had again"
  ],
  "sad_for_me": [
    "i'm sad i gave my best years to the wrong person",
    "i'm sad i lost myself trying to keep you",
    "i'm sad i wasted love on someone who didn't deserve it",
    "i'm sad i changed for someone who never appreciated it",
    "i'm sad i gave you power to destroy me",
    "i'm sad i sacrificed so much for so little",
    "i'm sad i ignored myself to prioritize you",
    "i'm sad i can't get back the time i lost",
    "i'm sad i believed in us when you didn't",
    "i'm sad i let you make me forget my worth"
  ],

  // Shame subcategories
  "ashamed": [
    "i'm ashamed of how easily i let you break me",
    "i'm ashamed i stayed when i should've run",
    "i'm ashamed of the person i became for you",
    "i'm ashamed i ignored every warning sign",
    "i'm ashamed of how desperate i was for your love",
    "i'm ashamed i let you treat me like that",
    "i'm ashamed of how long i believed your lies",
    "i'm ashamed i sacrificed my dignity for you",
    "i'm ashamed of how much i tolerated",
    "i'm ashamed i lost myself trying to keep you"
  ],
  "proud_myself": [
    "i'm proud i finally chose myself",
    "i'm proud i survived losing you",
    "i'm proud i'm healing without your help",
    "i'm proud i found strength i didn't know i had",
    "i'm proud i walked away when staying was easier",
    "i'm proud i'm rebuilding from the ruins you left",
    "i'm proud i'm learning to love myself again",
    "i'm proud i no longer need your validation",
    "i'm proud of the person i'm becoming without you",
    "i'm proud i turned my pain into power"
  ],
  "you_should_ashamed": [
    "you should be ashamed of how you treated someone who loved you",
    "you should be ashamed of the lies you told so easily",
    "you should be ashamed of how you broke someone who trusted you",
    "you should be ashamed of using my love against me",
    "you should be ashamed of how little you fought for us",
    "you should be ashamed of the person you showed you really are",
    "you should be ashamed of how easily you gave up on us",
    "you should be ashamed of the damage you caused without care",
    "you should be ashamed of how you made me question my worth",
    "you should be ashamed of turning love into a weapon"
  ],
  "both_should_ashamed": [
    "we should both be ashamed of what we let us become",
    "we're both guilty of destroying something beautiful",
    "we should both be ashamed of how we hurt each other",
    "we're both responsible for this mess we made",
    "we should both be ashamed we didn't try harder",
    "we're both guilty of giving up too easily",
    "we should both be ashamed of the toxicity we created",
    "we're both responsible for the love we destroyed",
    "we should both be ashamed we let pride win",
    "we're both guilty of failing each other"
  ],
  "no_one_ashamed": [
    "nobody should be ashamed for trying to make it work",
    "there's no shame in loving someone who couldn't love you back",
    "nobody should be ashamed for outgrowing someone",
    "there's no shame in choosing yourself over staying broken",
    "nobody should be ashamed for having standards",
    "there's no shame in walking away from toxicity",
    "nobody should be ashamed for needing more",
    "there's no shame in admitting it's over",
    "nobody should be ashamed for wanting better",
    "there's no shame in prioritizing your peace"
  ],

  // Thank You subcategories
  "thank_you": [
    "thank you for showing me what real love shouldn't look like",
    "thank you for the memories even though they haunt me",
    "thank you for loving me in the only way you knew how",
    "thank you for trying even though we failed",
    "thank you for the time we had before it ended",
    "thank you for the lessons wrapped in heartbreak",
    "thank you for making me who i am today",
    "thank you for the good days before the bad ones",
    "thank you for showing me i could feel deeply",
    "thank you for being part of my story"
  ],
  "no_thanks_needed": [
    "you don't owe me thanks, you owe me truth",
    "i don't need your thanks, i needed your effort",
    "your thanks mean nothing without action",
    "i don't want thanks, i wanted you to stay",
    "you don't need to thank me, you needed to love me",
    "i don't need appreciation, i needed commitment",
    "your thanks won't fix what you broke",
    "i don't want thanks, i wanted honesty",
    "you don't owe me thanks, you owed me respect",
    "i don't need your thanks, i needed your presence"
  ],
  "thank_pain": [
    "thank you for the pain that taught me my strength",
    "thank you for hurting me enough to finally leave",
    "thank you for the suffering that led to growth",
    "thank you for breaking me so i could rebuild better",
    "thank you for the heartbreak that showed me my worth",
    "thank you for the tears that washed away my illusions",
    "thank you for the loneliness that taught me self-love",
    "thank you for the emptiness that i learned to fill myself",
    "thank you for the darkness that made me find my own light",
    "thank you for breaking me in ways that made me unbreakable"
  ],
  "thank_memories": [
    "thank you for memories i'll cherish even through the pain",
    "thank you for moments that made me believe in magic",
    "thank you for experiences that shaped who i am",
    "thank you for the laughter before the tears",
    "thank you for adventures we took together",
    "thank you for the joy before the heartbreak",
    "thank you for happiness i got to experience with you",
    "thank you for the peace before the storm",
    "thank you for love even if it didn't last",
    "thank you for the beautiful before the broken"
  ],
  "thank_leaving": [
    "thank you for leaving, it forced me to find myself",
    "thank you for walking away, i found my strength",
    "thank you for setting me free even though it hurt",
    "thank you for ending it before we destroyed each other more",
    "thank you for the closure of knowing you're gone",
    "thank you for leaving, now i can finally heal",
    "thank you for walking away, it saved me from myself",
    "thank you for choosing to leave, i choose to thrive",
    "thank you for leaving, you gave me back to me",
    "thank you for walking away, i learned i don't need you"
  ],

  // Closure subcategories
  "need_answers": [
    "i need to know why i wasn't enough",
    "i need answers to stop replaying everything",
    "i need to understand what changed",
    "i need to know if any of it was real",
    "i need closure to stop the what-ifs",
    "i need to know where we went wrong",
    "i need answers to finally let go",
    "i need to understand so i can heal",
    "i need to know if you ever truly loved me",
    "i need closure to stop blaming myself"
  ],
  "dont_need_answers": [
    "i don't need your excuses anymore",
    "i don't need to know why, i just need to move on",
    "i don't need your explanation, i need my peace",
    "i don't need closure from you, i'll create my own",
    "i don't need answers, your actions said enough",
    "i don't need the truth, i already know it",
    "i don't need your words, i need my healing",
    "i don't need closure, i need to close this chapter",
    "i don't need anything from you but distance",
    "i don't need your reasons, i have my own now"
  ],
  "need_understand": [
    "i need to understand how we fell apart",
    "i need to understand what i did wrong",
    "i need to understand why you gave up",
    "i need to understand to stop the pain",
    "i need to understand so i don't repeat this",
    "i need to understand to forgive myself",
    "i need to understand to trust again",
    "i need to understand how love became hate",
    "i need to understand to find peace",
    "i need to understand to finally breathe"
  ],
  "need_move_on": [
    "i need to move on before you destroy me completely",
    "i need to let go even though it's tearing me apart",
    "i need to move forward without looking back",
    "i need to move on for my own survival",
    "i need to let go before i lose myself entirely",
    "i need to move on even though i still love you",
    "i need to leave you in the past where you belong",
    "i need to move forward to save what's left of me",
    "i need to let go before the memories kill me",
    "i need to move on because staying here is death"
  ],
  "need_closure": [
    "i need closure to stop the bleeding",
    "i need an ending so i can start healing",
    "i need closure to close this wound",
    "i need finality to find peace",
    "i need closure to stop waiting for you",
    "i need an ending to write a new beginning",
    "i need closure to stop loving you",
    "i need finality to let you go",
    "i need closure to move on with my life",
    "i need an ending that feels like one"
  ],
  "never_got_closure": [
    "you left without giving me closure",
    "you disappeared and took all my answers with you",
    "i never got to ask you why",
    "you left me with questions that haunt me",
    "i never got the goodbye i deserved",
    "you never explained and that's the cruelest part",
    "i never got closure and it's killing me",
    "you left without a word and i'm still waiting",
    "i never got the ending that made sense",
    "you took closure with you when you left"
  ],
  "seeking_closure": [
    "i'm desperately seeking the closure you won't give",
    "i'm searching for answers in empty spaces",
    "i'm hunting for closure in our old messages",
    "i'm seeking peace in unanswered questions",
    "i'm looking for closure that doesn't exist",
    "i'm chasing the closure i'll never get",
    "i'm seeking endings in our beginnings",
    "i'm searching for peace you can't give me",
    "i'm looking for closure in every memory",
    "i'm seeking answers i already know"
  ],
  "closure_impossible": [
    "closure is impossible when you refuse to give it",
    "i'll never have closure from someone who won't talk",
    "closure is impossible without truth",
    "i can't get closure from a ghost",
    "closure is impossible when you disappeared",
    "i'll never have closure from unfinished conversations",
    "closure is impossible when you left me hanging",
    "i can't find closure in silence",
    "closure is impossible without answers",
    "i'll never have closure from someone who stopped caring"
  ],
  "found_own_closure": [
    "i found closure in accepting i'll never get it from you",
    "i created my own ending since you didn't give me one",
    "i found peace in letting go of needing answers",
    "i built my own closure from the ruins you left",
    "i found healing in accepting the silence",
    "i created closure by choosing myself",
    "i found peace by writing my own ending",
    "i built closure from self-love, not your words",
    "i found my own way to say goodbye",
    "i created closure by finally moving on"
  ],

  // Other subcategories
  "other_feeling": [
    "i feel something that doesn't have a name yet",
    "there's an emotion i've never felt before",
    "i'm feeling something words can't capture",
    "there's a feeling too complex to label",
    "i feel something between love and hate",
    "there's an emotion stuck in my throat",
    "i'm feeling something i don't understand",
    "there's a pain that isn't quite sadness",
    "i feel something beyond what i can express",
    "there's an emotion too raw to name"
  ],
  "different_emotion": [
    "i'm feeling something i didn't expect to feel",
    "there's a new emotion replacing the old one",
    "i feel different than i thought i would",
    "something shifted and i don't recognize this feeling",
    "i'm experiencing emotions i never knew existed",
    "there's a strange new feeling taking over",
    "i feel something unfamiliar in my chest",
    "there's an unexpected emotion surfacing",
    "i'm feeling things in a whole new way",
    "something changed and my emotions followed"
  ],
  "something_else": [
    "there's something beneath the surface i can't reach",
    "i feel like there's more to this story",
    "there's something hidden you're not telling me",
    "i sense there's a deeper truth here",
    "there's something else going on i don't understand",
    "i feel like you're hiding something from me",
    "there's more to your words than what you're saying",
    "i sense something you won't admit",
    "there's a hidden truth beneath your lies",
    "i feel something unspoken between us"
  ],
  "cant_explain": [
    "words aren't enough for what i'm feeling",
    "i can't explain this ache in my chest",
    "there are no words for this kind of hurt",
    "i can't articulate the weight i'm carrying",
    "words fail to describe what you did to me",
    "i can't explain why i still love you",
    "there's no way to describe this emptiness",
    "i can't put into words how broken i feel",
    "no explanation can capture this pain",
    "i can't express how much i'm hurting"
  ],
  "complicated": [
    "we're too complicated to be simple",
    "our love is too complex to explain",
    "this situation is more layered than it seems",
    "we're complicated in ways that hurt",
    "our story is too intricate to summarize",
    "this feeling is complicated and messy",
    "we're tangled in ways i can't untangle",
    "our love is complicated by our pain",
    "this is too complex for simple answers",
    "we're complicated because we're broken"
  ],

  // Devotion subcategories
  "devoted_to_you": [
    "i'm devoted to you in ways that scare me",
    "my devotion to you borders on obsession",
    "i'm devoted to loving you even when it hurts",
    "every breath i take is devoted to you",
    "i'm devoted to you beyond reason or sanity",
    "my devotion to you is my greatest weakness",
    "i'm devoted to you in ways i can't explain",
    "my entire existence is devoted to loving you",
    "i'm devoted to you more than i'm devoted to myself",
    "my devotion to you will be my undoing"
  ],
  "worship_your_existence": [
    "i worship you like you're the only god i know",
    "your existence is my religion",
    "i worship every piece of you even the broken parts",
    "you are the altar i pray at daily",
    "i worship the ground you walk on and it destroys me",
    "your existence is all i live for",
    "i worship you in ways that aren't healthy",
    "you are my gospel and my salvation",
    "i worship everything about you even what hurts me",
    "your existence is my reason for breathing"
  ],
  "you_are_my_religion": [
    "you became my religion and now i'm lost without faith",
    "loving you is the only prayer i know",
    "you're my religion and i'm a devoted worshipper",
    "i built a temple around you in my heart",
    "you're the god i pray to in my darkest moments",
    "loving you is my daily devotion",
    "you're my religion and losing you is losing my faith",
    "i worship at the altar of your memory",
    "you're the scripture i read when i can't sleep",
    "loving you is the only commandment i follow"
  ],
  "unconditional_love": [
    "i love you unconditionally and it's killing me",
    "my love for you has no limits even when it should",
    "i love you without conditions and you took advantage",
    "i love you unconditionally even when you don't deserve it",
    "my love has no boundaries and you crossed them all",
    "i love you without expectations and got nothing back",
    "i love you unconditionally even when you hurt me",
    "my love for you is limitless and that's the problem",
    "i love you without demands and you demanded everything",
    "i love you unconditionally even when it destroys me"
  ],
  "would_die_for_you": [
    "i'd die for you and part of me already has",
    "i would sacrifice everything and i did",
    "i'd give my life for you without hesitation",
    "i would die for you and you wouldn't even notice",
    "i'd risk everything for you even my own sanity",
    "i would lose everything for you and i almost did",
    "i'd abandon the world for you in a heartbeat",
    "i would die for you but living without you is worse",
    "i'd surrender my soul for you gladly",
    "i would die for you but you're killing me slowly anyway"
  ],

  // Hope subcategories
  "hope_for_us": [
    "i still stupidly hope we can fix this",
    "hope for us is all i have left",
    "i'm clinging to hope even though it's fading",
    "i hope we can start over but i know we can't",
    "hope for us is the only thing keeping me alive",
    "i'm holding onto hope that's probably foolish",
    "i hope we can heal but the wounds are too deep",
    "hope for us feels like a cruel joke now",
    "i'm hoping for a miracle that won't come",
    "i hope we can be happy again even though i don't believe it"
  ],
  "hope_you_return": [
    "i hope you come back even though you won't",
    "i hope you realize what you lost before it's too late",
    "i'm hoping you'll remember us and miss me",
    "i hope you find your way back to me someday",
    "i'm foolishly hoping you'll choose me again",
    "i hope you miss me as much as i miss you",
    "i'm hoping you'll want me back eventually",
    "i hope you need me again like i still need you",
    "i'm hoping you still love me somewhere deep down",
    "i hope one day you'll regret leaving me"
  ],
  "hope_for_healing": [
    "i hope we both find a way to heal from this",
    "i'm hoping time actually heals these wounds",
    "i hope we both learn to love again someday",
    "i'm hoping we can both find happiness apart",
    "i hope healing is possible even though it hurts",
    "i'm hoping we both grow from this pain",
    "i hope we both find peace even if it's not together",
    "i'm hoping this suffering leads to something better",
    "i hope we both find ourselves again eventually",
    "i'm hoping healing is worth the agony"
  ],
  "hope_is_fading": [
    "hope is slipping through my fingers like sand",
    "i can feel hope dying a little more each day",
    "hope is fading and i'm terrified of what's left",
    "i'm losing hope and i don't know how to get it back",
    "hope is disappearing and darkness is taking over",
    "i can feel hope leaving me empty",
    "hope is dying and taking me with it",
    "i'm watching hope fade into nothing",
    "hope is slipping away and i can't hold on",
    "i'm losing hope and i'm scared"
  ],
  "never_give_up_hope": [
    "i refuse to give up hope even when it's foolish",
    "i'll never stop believing even when i should",
    "i can't give up hope even though it's killing me",
    "i refuse to lose hope no matter how much it hurts",
    "i'll never stop hoping even when it's hopeless",
    "i can't give up on us even when i should",
    "i refuse to stop believing in love",
    "i'll never give up hope for happiness",
    "i can't stop hoping even when hope is gone",
    "i refuse to let go of hope for us"
  ],

  // Longing subcategories
  "ache_for_you": [
    "i ache for you in ways that steal my breath",
    "i ache for you so deeply it's become part of me",
    "my bones ache with the weight of missing you",
    "i ache for you in the spaces between heartbeats",
    "i ache for you like a phantom limb i can't forget",
    "my whole body aches with the absence of you",
    "i ache for you in dreams that turn to nightmares",
    "i ache for you with a pain that never dulls",
    "my soul aches for yours in ways i can't explain",
    "i ache for you and the ache is all i have left"
  ],
  "desperate_yearning": [
    "i yearn for you with a desperation that terrifies me",
    "my yearning for you consumes every waking moment",
    "i yearn for you so desperately it hurts to breathe",
    "the yearning never stops, never fades, never lets go",
    "i yearn for you with my entire broken being",
    "desperate yearning is my constant companion now",
    "i yearn for you in ways that aren't healthy",
    "the yearning eats away at me daily",
    "i yearn for you hopelessly, endlessly, painfully",
    "my yearning for you is killing me slowly"
  ],
  "craving_your_touch": [
    "i crave your touch like an addict craves their fix",
    "my skin craves yours in ways that make me ache",
    "i crave your touch so badly it's physical pain",
    "the craving for your touch never leaves me",
    "i crave your hands on me like i crave oxygen",
    "my body craves yours in devastating ways",
    "i crave your touch even though it's gone forever",
    "the craving is constant, painful, and endless",
    "i crave your touch like it's the only thing that matters",
    "my body craves yours and it's destroying me"
  ],
  "starving_for_you": [
    "i'm starving for you and nothing else satisfies",
    "i'm starving for your love like it's sustenance",
    "my soul is starving for yours",
    "i'm starving for your presence and dying without it",
    "i'm starving for you and wasting away",
    "my heart is starving for yours and nothing else feeds it",
    "i'm starving for your voice saying my name",
    "i'm starving for the warmth you took with you",
    "my entire being is starving for yours",
    "i'm starving for you and slowly fading"
  ],
  "endless_desire": [
    "my desire for you is endless and exhausting",
    "i feel desire that never fades or lessens",
    "endless desire for you is my curse",
    "i carry desire that won't let me rest",
    "my desire for you is bottomless and consuming",
    "endless desire keeps me up at night",
    "i live with desire that has no end",
    "my desire for you is infinite and painful",
    "endless desire is all i have left of us",
    "i carry desire for you that time can't kill"
  ],

  // Nostalgia subcategories
  "remember_good_times": [
    "i remember when loving you didn't hurt",
    "i remember when we laughed more than we cried",
    "i remember when we were whole instead of broken",
    "i remember when being together felt like coming home",
    "i remember when we were in love before the pain",
    "i remember when we were free before the chains",
    "i remember when we were young and believed in forever",
    "i remember when we were innocent before reality hit",
    "i remember when we were hopeful about our future",
    "i remember when we felt alive together"
  ],
  "miss_our_past": [
    "i miss the version of us that believed we'd make it",
    "i miss the life we thought we were building",
    "i miss when our dreams aligned",
    "i miss the way we loved before it turned toxic",
    "i miss the past when we still tried",
    "i miss the future that died with us",
    "i miss the happiness before the heartbreak",
    "i miss the peace before the war",
    "i miss the trust before the lies",
    "i miss the bond before it shattered"
  ],
  "better_days": [
    "i remember better days when hope still lived",
    "i remember when everything wasn't so complicated",
    "i remember when love felt simple and pure",
    "i remember when love was enough to fix anything",
    "i remember when we were happy without trying",
    "i remember when we were whole people together",
    "i remember when being together was all we needed",
    "i remember when loving you was easy",
    "i remember when we were free from this pain",
    "i remember when the future looked bright"
  ],
  "golden_memories": [
    "i hold onto golden memories that now feel like lies",
    "golden memories are all i have left of us",
    "i treasure memories that hurt to remember",
    "i protect memories that are slowly fading",
    "i keep golden memories that cut like glass",
    "i love memories that make me cry",
    "i miss when memories were being made not mourned",
    "i cling to memories knowing they'll never be enough",
    "golden memories are beautiful and painful at once",
    "i live in memories because the present is unbearable"
  ],
  "wish_we_could_go_back": [
    "i wish we could rewrite our ending",
    "i wish we could go back before everything fell apart",
    "i wish we could return to when love was enough",
    "i wish we could go back to simpler, happier times",
    "i wish we could redo it all and get it right",
    "i wish we could return to when we were truly happy",
    "i wish we could go back to being whole together",
    "i wish we could return to when we believed in us",
    "i wish we could go back before the damage was done",
    "i wish we could return to when leaving wasn't an option"
  ],

  // Vulnerability subcategories
  "opening_my_heart": [
    "i'm opening my heart knowing you could break it",
    "i'm showing you parts of me no one else sees",
    "i'm giving you my heart please don't drop it",
    "i'm sharing my deepest fears with you",
    "i'm revealing my scars and hoping you won't run",
    "i'm exposing my soul and praying you'll stay",
    "i'm baring my heart despite my terror",
    "i'm offering you my vulnerability as trust",
    "i'm presenting my broken pieces to you",
    "i'm showing you my heart knowing it's fragile"
  ],
  "showing_weakness": [
    "i'm showing you my weakness and it terrifies me",
    "i'm revealing parts of me i usually hide",
    "i'm exposing my soft underbelly to you",
    "i'm sharing my insecurities hoping you'll understand",
    "i'm giving you my weakness please don't use it against me",
    "i'm showing you where i'm broken",
    "i'm revealing my fears and hoping you'll protect them",
    "i'm exposing my vulnerabilities as an act of trust",
    "i'm baring my weaknesses because i trust you",
    "i'm showing you my fragile parts please be gentle"
  ],
  "need_protection": [
    "i need you to protect my heart from more breaking",
    "i need you to keep my secrets safe",
    "i need you to protect what's left of my soul",
    "i need you to guard my feelings carefully",
    "i need you to protect me from myself",
    "i need you to keep my vulnerabilities safe",
    "i need you to protect my dreams from shattering",
    "i need you to guard my hope from dying",
    "i need you to protect my trust from breaking again",
    "i need you to keep my heart safe this time"
  ],
  "trust_you_completely": [
    "i trust you completely and it scares me",
    "i'm trusting you with everything i have",
    "i trust you with my broken heart",
    "i'm trusting you with my scarred soul",
    "i trust you with my life despite my fear",
    "i'm trusting you with my uncertain future",
    "i trust you with my painful past",
    "i'm trusting you with my fragile present",
    "i trust you with dreams i'm afraid to voice",
    "i'm trusting you completely and praying i'm not wrong"
  ],
  "exposed_and_fragile": [
    "i feel exposed like a nerve without skin",
    "i'm vulnerable in ways that terrify me",
    "i feel defenseless and it's terrifying",
    "i'm naked emotionally and it hurts",
    "i feel unprotected and raw",
    "i'm exposed and you could destroy me easily",
    "i feel fragile like i could shatter any moment",
    "i'm vulnerable and hoping you'll be gentle",
    "i feel exposed in ways i can't take back",
    "i'm fragile and one wrong move will break me"
  ],

  // Betrayal subcategories
  "you_betrayed_me": [
    "you betrayed me after i gave you everything",
    "i trusted you with my secrets and you used them against me",
    "you betrayed the trust i've never given anyone else",
    "i thought you were safe and you destroyed me",
    "you betrayed me in ways i didn't think possible",
    "i opened my soul to you and you weaponized it",
    "you betrayed me after i made myself vulnerable for you",
    "i thought you were different but you proved me wrong",
    "you betrayed the person who loved you most",
    "i never thought you'd be the one to break me"
  ],
  "i_betrayed_you": [
    "i broke your trust and i hate myself for it",
    "i betrayed everything we built together",
    "i destroyed what we had and i can't take it back",
    "i stabbed you in the back when you deserved better",
    "i became the person i promised i'd never be",
    "i broke promises i meant to keep",
    "i betrayed your love when you gave me everything",
    "i destroyed our future with my own hands",
    "i broke your heart and mine in the process",
    "i betrayed you and lost myself too"
  ],
  "mutual_betrayal": [
    "we betrayed each other in equal measure",
    "we both broke trust that can't be rebuilt",
    "we destroyed each other while destroying us",
    "we betrayed the love we swore to protect",
    "we both broke promises we meant to keep",
    "we lied to each other and to ourselves",
    "we hurt each other beyond repair",
    "we betrayed the future we planned together",
    "we destroyed everything we built",
    "we broke each other trying not to break"
  ],
  "trust_destroyed": [
    "you destroyed my ability to trust anyone",
    "i can never trust the way i trusted you",
    "you destroyed my faith in love itself",
    "i can't trust my own judgment after trusting you",
    "you destroyed my trust and i don't know how to rebuild it",
    "i can never believe in forever after this",
    "you destroyed my ability to hope",
    "i can't trust promises after you broke yours",
    "you destroyed my faith in people",
    "i can never trust words after your lies"
  ],
  "betrayal_by_friend": [
    "you were my friend before you became my betrayer",
    "i trusted you with everything as a friend",
    "you betrayed a friendship i thought was unbreakable",
    "i thought our bond meant something to you",
    "you betrayed the loyalty i gave you",
    "i never thought a friend would hurt me this way",
    "you betrayed years of friendship in one moment",
    "i trusted you as a friend and you destroyed me",
    "you were supposed to be safe as my friend",
    "you betrayed a friendship i'll never risk again"
  ],

  // Emptiness subcategories
  "empty_without_you": [
    "you took yourself and left me hollow",
    "emptiness echoes where you used to be",
    "i am a shell of who i was with you",
    "you left and took my wholeness with you",
    "empty rooms remind me of empty hearts"
  ],
  "hollow_inside": [
    "hollowness lives where my heart should be",
    "i am carved out and echoing",
    "hollow is the sound of my name without you",
    "i am empty space pretending to be person",
    "hollowness fills every corner of my being"
  ],
  "void_in_heart": [
    "there's a you-shaped void in my chest",
    "the void grows larger every day",
    "my heart is a black hole where you used to be",
    "void is the only word for this absence",
    "the void consumes everything good"
  ],
  "numb_and_empty": [
    "numbness is my default setting now",
    "i feel nothing which is worse than everything",
    "empty and numb is my natural state",
    "numbness protects me from the emptiness",
    "i am void of feeling void of you"
  ],
  "emptiness_consumes": [
    "emptiness eats me from the inside out",
    "the void grows hungrier each day",
    "emptiness is a living thing inside me",
    "i am being consumed by my own absence",
    "emptiness feeds on what's left of me"
  ],

  // Obsession subcategories
  "cant_stop_thinking": [
    "i can't stop thinking about you and it's driving me insane",
    "you're in my head constantly and i can't escape",
    "i replay every moment obsessively",
    "i can't stop thinking about us even when it hurts",
    "thoughts of you consume me every second",
    "i can't stop obsessing over what we lost",
    "you live in my mind rent-free and it's torture",
    "i can't stop thinking about what could have been",
    "every thought leads back to you somehow",
    "i'm trapped in an endless loop of thinking about you"
  ],
  "consumed_by_you": [
    "you consume my every waking thought",
    "i'm consumed by memories that won't fade",
    "you've consumed me entirely and there's nothing left",
    "i'm consumed by desire that never quiets",
    "you consume me like a fire i can't put out",
    "i'm consumed by need that's never satisfied",
    "you consume every part of me that's left",
    "i'm consumed by longing that has no end",
    "you consume me completely and i'm losing myself",
    "i'm consumed by you and there's no escape"
  ],
  "unhealthy_fixation": [
    "my fixation on you is destroying me but i can't stop",
    "i know this obsession is toxic but i need it",
    "my addiction to you is dangerous and i'm aware",
    "i know i need to let go but i'm fixated",
    "this obsession is unhealthy but it's all i have",
    "i know i'm too fixated but i can't help it",
    "my obsession with you is killing me slowly",
    "i'm fixated in ways that scare me",
    "i know this isn't healthy but i can't stop",
    "my obsession has become my identity"
  ],
  "obsessed_with_memories": [
    "i'm obsessed with replaying every moment we had",
    "i dissect our memories looking for where it went wrong",
    "i'm obsessed with remembering every detail",
    "memories of us consume me day and night",
    "i'm obsessed with moments that are gone forever",
    "i replay our past like a broken record",
    "i'm obsessed with memories that hurt to remember",
    "i can't stop analyzing every memory we made",
    "i'm obsessed with what we were before it ended",
    "memories of you are my obsession and my prison"
  ],
  "addicted_to_you": [
    "i'm addicted to you like you're my drug",
    "you're my addiction and i can't get clean",
    "i'm addicted to the high of loving you",
    "you're my addiction and withdrawal is killing me",
    "i'm addicted to you and i need my fix",
    "you're the addiction i can't shake",
    "i'm addicted to the pain of missing you",
    "you're my drug and i'm dependent",
    "i'm addicted in ways that aren't healthy",
    "you're my addiction and sobriety terrifies me"
  ],

  // Passion subcategories
  "burning_desire": [
    "desire for you burns through me constantly",
    "i feel burning desire that never cools",
    "you ignite a fire in me that won't die",
    "burning desire consumes me night and day",
    "i carry desire that burns like wildfire",
    "the burning never stops it only intensifies",
    "desire for you burns away everything else",
    "i live with fire that won't be extinguished",
    "burning desire is my constant state",
    "you set me ablaze and i'm still burning"
  ],
  "wild_love": [
    "my love for you is wild and untamed",
    "i feel wild reckless love that scares me",
    "wild love courses through my veins for you",
    "my love is wild like a storm i can't control",
    "i carry wild love that refuses to be contained",
    "wild untamed love is what i feel for you",
    "my love is wild and it's destroying me beautifully",
    "i feel love so wild it's dangerous",
    "wild passionate love is all i know with you",
    "my love for you is wildly out of control"
  ],
  "fierce_attraction": [
    "fierce attraction pulls me to you constantly",
    "i feel attraction so fierce it's painful",
    "fierce magnetic pull draws me to you always",
    "i'm fiercely attracted in ways i can't explain",
    "attraction to you is fierce and relentless",
    "i feel fierce draw to you i can't resist",
    "fierce attraction consumes my every thought",
    "i'm fiercely attracted even when i shouldn't be",
    "attraction to you is fierce and all-consuming",
    "i feel fierce pull toward you that won't fade"
  ],
  "passionate_fire": [
    "passion for you burns like eternal flame",
    "passionate fire rages inside me for you",
    "you ignite passionate fire i can't control",
    "passionate flames consume me when i think of you",
    "fire of passion burns brighter every day",
    "passionate fire for you never dims",
    "i burn with passion that won't be quenched",
    "passionate fire is what you left in me",
    "flames of passion still burn despite everything",
    "passionate fire for you is my curse and gift"
  ],
  "intense_connection": [
    "our connection was intense beyond words",
    "i felt connection so intense it scared me",
    "intense bond between us can't be severed",
    "connection we had was intensely profound",
    "i feel intense connection that transcends distance",
    "our connection was intense and irreplaceable",
    "intense bond we shared haunts me still",
    "connection between us was intensely real",
    "i felt connection so intense it changed me",
    "intense connection we had will never be replicated"
  ],

  // Pride subcategories
  "proud_of_us": [
    "i'm proud of what we had even though it ended",
    "i'm proud we loved deeply even if we failed",
    "i'm proud of memories we made before the pain",
    "i'm proud we tried even though we fell apart",
    "i'm proud of the dreams we dared to share",
    "i'm proud of what we built before it crumbled",
    "i'm proud we loved hard even though it hurt",
    "i'm proud of the happiness we found together",
    "i'm proud we had something real however briefly",
    "i'm proud of the love we shared before it died"
  ],
  "too_proud_to_beg": [
    "i'm too proud to beg even though i'm dying inside",
    "pride won't let me crawl back even though i want to",
    "i'm too proud to beg for love i shouldn't have to earn",
    "pride keeps me from admitting how much i need you",
    "i'm too proud to show you i'm falling apart",
    "pride won't let me admit i made mistakes",
    "i'm too proud to ask for what you should give freely",
    "pride stops me from showing my vulnerability",
    "i'm too proud to beg even though pride is killing me",
    "i won't beg for love pride is all i have left"
  ],
  "swallowing_pride": [
    "i'm swallowing my pride and it tastes like defeat",
    "i'm choking down pride to save us",
    "pride means nothing if losing you is the cost",
    "i'm sacrificing pride because love matters more",
    "i'll swallow my pride if it means keeping you",
    "pride can die if it saves what we have",
    "i'm letting go of pride to hold onto you",
    "i'm destroying my pride to rebuild us",
    "i'll bury my pride if you'll just stay",
    "pride is worthless compared to losing you"
  ],
  "pride_before_fall": [
    "my pride destroyed us before i realized",
    "pride was my downfall and our ending",
    "i let pride ruin the best thing i had",
    "pride killed our love and i let it happen",
    "my pride destroyed what we could have been",
    "pride was more important to me than you and i regret it",
    "i chose pride over love and lost everything",
    "pride destroyed our future and i can't forgive myself",
    "my pride killed us and i was too blind to see",
    "pride was my weapon and it destroyed us both"
  ],
  "damaged_pride": [
    "you damaged my pride when you chose someone else",
    "my pride took a hit when you left me",
    "you destroyed my pride when you stopped loving me",
    "my pride shattered when i wasn't enough",
    "you wounded my pride by making me beg",
    "my pride broke when i realized you didn't care",
    "you crushed my pride by treating me like nothing",
    "my pride died when you replaced me so easily",
    "you destroyed my pride by proving i was wrong",
    "my pride was obliterated when you didn't fight for us"
  ],

  // Yearning subcategories
  "yearn_for_touch": [
    "i yearn for your touch like i yearn for air",
    "my skin yearns for yours desperately",
    "i yearn for your hands on me constantly",
    "yearning for your touch consumes me",
    "i yearn for your touch that's gone forever",
    "my body yearns for yours endlessly",
    "i yearn for your touch with physical ache",
    "yearning for your touch is my torture",
    "i yearn for your hands that won't hold me again",
    "my whole being yearns for your touch"
  ],
  "desperate_need": [
    "desperate need for you claws at me",
    "i need you desperately and it's destroying me",
    "desperate need consumes my every moment",
    "i live in desperate need that's never satisfied",
    "desperate need for you is killing me slowly",
    "i carry desperate need that weighs me down",
    "desperate need for you won't let me breathe",
    "i'm desperate for you in ways that scare me",
    "desperate need follows me everywhere",
    "i'm drowning in desperate need for you"
  ],
  "soul_yearning": [
    "my soul yearns for yours across the distance",
    "soul-deep yearning aches in my chest",
    "i feel soul yearning that's bottomless",
    "my soul yearns for connection we lost",
    "soul yearning lives in my bones",
    "i carry soul yearning in every breath",
    "my soul yearns for yours endlessly",
    "soul-deep yearning won't let me rest",
    "i feel yearning in the depths of my soul",
    "my soul yearns for yours like a prayer"
  ],
  "yearning_for_past": [
    "i yearn for the past when we were happy",
    "i yearn for who we were before pain",
    "i yearn for the love we had before it broke",
    "i yearn for happiness that's gone forever",
    "i yearn for peace we destroyed together",
    "i yearn for trust that can't be rebuilt",
    "i yearn for the bond we shattered",
    "i yearn for the future that died with us",
    "i yearn for dreams that won't come true",
    "i yearn for the life we'll never have"
  ],
  "unfulfilled_yearning": [
    "unfulfilled yearning is my constant companion",
    "i carry yearning that will never be satisfied",
    "unfulfilled yearning eats away at me",
    "i live with yearning that has no resolution",
    "unfulfilled yearning is my curse",
    "i feel yearning that will never be fulfilled",
    "unfulfilled yearning defines my existence now",
    "i carry yearning with no hope of satisfaction",
    "unfulfilled yearning is all i have left",
    "i live in state of eternal unfulfilled yearning"
  ]
};
