"use client";
import React, { useState, useEffect, useMemo } from "react";

const TypingEffect: React.FC = () => {
  const messages = useMemo(
    () => [
      "I wish I said no more often.",
      "You inspire me to be nothing like you.",
      "We were just strangers with memories.",
      "I miss the old me, before you.",
      "Some things are better left unsaid.",
      "You never realized, did you?",
      "I was always second choice.",
      "I should have walked away sooner.",
      "You never fought for me.",
      "It still hurts, but I hide it well.",
      "The horizon swallowed your light.",
      "I chase your echo in dreams.",
      "The stillness cuts me deepest.",
      "Your warmth faded too soon.",
      "I wander where we stood.",
      "The air feels thin without you.",
      "Your whispers haunt my quiet.",
      "I lost my north with you.",
      "The dusk paints your absence.",
      "Your hands slip from memory.",
      "I linger in your yesterday.",
      "The tide took your promise.",
      "Your gaze still pierces me.",
      "I stumble through your void.",
      "The frost mirrors my heart.",
      "Your breath was my rhythm.",
      "I seek you in the haze.",
      "The earth holds your shadow.",
      "Your love was my tide.",
      "I unravel without your thread.",
      "The hills echo your silence.",
      "Your absence carves my days.",
      "I lost my dawn with you.",
      "The mist hides your face.",
      "Your voice was my compass.",
      "I drift in your wake.",
      "The trees mourn your steps.",
      "Your touch was my horizon.",
      "I crumble beneath your memory.",
      "The sky forgot your color.",
      "Your name stains my soul.",
      "I lost my shelter with you.",
      "The waves whisper your goodbye.",
      "Your eyes were my refuge.",
      "I falter in your absence.",
      "The dark steals your outline.",
      "Your love was my flame.",
      "I lost my spark with you.",
      "The clouds carry your scent.",
      "Your silence deafens my world.",
      "I search the wind for you.",
      "The night buries your smile.",
      "Your presence was my peace.",
      "I lost my balance with you.",
      "The dawn echoes your loss.",
      "Your hands were my map.",
      "I wander your empty trails.",
      "The rain erases your mark.",
      "Your heart was my harbor.",
      "I sink in your distance.",
      "The stars blur your image.",
      "Your absence is my tide.",
      "I lost my anchor with you.",
      "The fog swallows your voice.",
      "Your love was my breath.",
      "I choke on your memory.",
      "The hills hide your shadow.",
      "Your touch was my calm.",
      "I fracture without your hold.",
      "The dusk mourns your name.",
      "Your eyes were my sky.",
      "I fall through your void.",
      "The wind steals your warmth.",
      "Your smile was my dawn.",
      "I lost my day with you.",
      "The tide buries your laugh.",
      "Your absence is my abyss.",
      "I trace your faded lines.",
      "The dark cloaks your love.",
      "Your voice was my shelter.",
      "I drift without your pull.",
      "The earth forgets your weight.",
      "Your hands were my haven.",
      "I break in your silence.",
      "The sky mourns your light.",
      "Your name is my fracture.",
      "I lost my roots with you.",
      "The mist blurs your form.",
      "Your love was my pulse.",
      "I fade in your absence.",
      "The trees whisper your loss.",
      "Your touch was my shore.",
      "I drown without your tide.",
      "The night shrouds your face.",
      "Your heart was my echo.",
      "I unravel in your quiet.",
      "The stars lose your glow.",
      "Your absence is my weight.",
      "I lost my fire with you.",
      "The waves mourn your breath.",
      "Your eyes were my depth.",
      "I sink beneath your shadow.",
      "The wind carries your void.",
      "Your smile was my anchor.",
      "I drift without your hold.",
      "The dusk hides your trace.",
      "Your love was my wing.",
      "I fall without your lift.",
      "The fog buries your warmth.",
      "Your voice was my tide.",
      "I fracture in your wake.",
      "The hills lose your echo.",
      "Your touch was my dawn.",
      "I fade without your light.",
      "The sky forgets your name.",
      "Your absence is my storm.",
      "I lost my calm with you.",
      "The rain drowns your scent.",
      "Your heart was my compass.",
      "I wander without your guide.",
      "The dark steals your laugh.",
      "Your hands were my peace.",
      "I break without your strength.",
      "The stars mourn your silence.",
      "Your love was my shore.",
      "I drift in your abyss.",
      "The mist hides your smile.",
      "Your absence is my chain.",
      "I lost my hope with you.",
      "The tide erases your steps.",
      "Your eyes were my flame.",
      "I dim without your spark.",
      "The wind buries your voice.",
      "Your touch was my refuge.",
      "I fracture without your care.",
      "The night cloaks your memory.",
      "Your heart was my haven.",
      "I sink without your lift.",
      "The sky loses your hue.",
      "Your name is my wound.",
      "I lost my breath with you.",
      "The waves steal your echo.",
      "Your love was my depth.",
      "I drown in your silence.",
      "The trees forget your touch.",
      "Your absence is my frost.",
      "I fade without your warmth.",
      "The dusk mourns your loss.",
      "Your smile was my tide.",
      "I drift without your pull.",
      "The fog swallows your light.",
      "Your voice was my anchor.",
      "I unravel without your hold.",
      "The hills blur your form.",
      "Your touch was my sky.",
      "I fall without your lift.",
      "The rain hides your shadow.",
      "Your heart was my dawn.",
      "I dim in your absence.",
      "The stars lose your trace.",
      "Your absence is my dark.",
      "I lost my way with you.",
      "The wind mourns your name.",
      "Your eyes were my peace.",
      "I break without your calm.",
      "The tide buries your love.",
      "Your hands were my shore.",
      "I sink without your guide.",
      "The night steals your glow.",
      "Your love was my compass.",
      "I wander in your void.",
      "The mist cloaks your laugh.",
      "Your absence is my weight.",
      "I lost my light with you.",
      "The waves drown your smile.",
      "Your touch was my flame.",
      "I fade without your spark.",
      "The sky forgets your breath.",
      "Your heart was my refuge.",
      "I fracture without your care.",
      "The dusk hides your warmth.",
      "Your name is my tide.",
      "I drift without your hold.",
      "The fog buries your eyes.",
      "Your love was my haven.",
      "I sink without your pull.",
      "The trees mourn your silence.",
      "Your absence is my wound.",
      "I lost my peace with you.",
      "The rain steals your echo.",
      "Your smile was my depth.",
      "I drown without your light.",
      "The wind cloaks your steps.",
      "Your touch was my anchor.",
      "I unravel without your strength.",
      "The night loses your form.",
      "Your heart was my sky.",
      "I fall without your lift.",
      "The stars blur your memory.",
      "Your absence is my frost.",
      "I fade without your warmth.",
      "The waves mourn your voice.",
      "Your love was my shore.",
      "I carved our ruin alone.",
      "The fracture was my handiwork.",
      "My hesitation lost your light.",
      "I let the spark die out.",
      "The fault threads through me.",
      "I turned away from you.",
      "My cowardice broke our bond.",
      "The shame is my own.",
      "I didn’t catch your fall.",
      "My blindness cost us both.",
      "The wreckage is my mark.",
      "I failed your quiet plea.",
      "My hands shaped this pain.",
      "The remorse is my echo.",
      "I didn’t shield your heart.",
      "My faltering tore us down.",
      "The sorrow stems from me.",
      "I wasn’t your safe place.",
      "My neglect lost your trust.",
      "The fault runs through my veins.",
      "I let the silence grow.",
      "My stubbornness hurt you first.",
      "The guilt is my anchor.",
      "I didn’t earn your faith.",
      "My arrogance dimmed your glow.",
      "The ruin is my legacy.",
      "I failed your tender hope.",
      "My indecision cut you deep.",
      "The blame clings to me.",
      "I let your warmth slip away.",
      "My pride severed our thread.",
      "The regret is my shroud.",
      "I didn’t see your breaking.",
      "My fears built this wall.",
      "The fault is my own stitch.",
      "I crushed your fragile dream.",
      "My silence was your wound.",
      "The guilt coils around me.",
      "I didn’t cradle your love.",
      "My choices dimmed your star.",
      "The sorrow is my harvest.",
      "I let the doubt take root.",
      "My ego bruised your soul.",
      "The remorse is my tide.",
      "I didn’t guard your smile.",
      "My fears locked you out.",
      "The fault is my own shadow.",
      "I shattered your gentle trust.",
      "My stillness broke your song.",
      "The guilt is my mirror.",
      "I didn’t hold you steady.",
      "My hands pushed you away.",
      "The ruin is my burden.",
      "I let your hope unravel.",
      "My pride drowned your voice.",
      "The regret is my chain.",
      "I didn’t feel your ache.",
      "My fears stole your peace.",
      "The fault is my own thread.",
      "I broke your tender spirit.",
      "My silence was your cage.",
      "The guilt is my storm.",
      "I didn’t lift your heart.",
      "My doubts buried our flame.",
      "The blame is my own weight.",
      "I let your light fade out.",
      "My pride tore your wings.",
      "The remorse is my frost.",
      "I didn’t hear your whisper.",
      "My fears sank your dreams.",
      "The fault is my own scar.",
      "I failed your quiet strength.",
      "My stillness hurt you most.",
      "The guilt is my own tide.",
      "I didn’t keep you whole.",
      "My choices stole your calm.",
      "The sorrow is my own seed.",
      "I let the dark take over.",
      "My ego crushed your hope.",
      "The regret is my own echo.",
      "I didn’t see your drift.",
      "My fears locked your love.",
      "The fault is my own fracture.",
      "I broke your fragile dawn.",
      "My silence was your loss.",
      "The guilt is my own shroud.",
      "I didn’t hold your light.",
      "My doubts drowned your spark.",
      "The blame is my own chain.",
      "I let your warmth escape.",
      "My pride bruised your heart.",
      "The remorse is my own shadow.",
      "I didn’t catch your tears.",
      "My fears built your cage.",
      "The fault is my own wound.",
      "I failed your steady gaze.",
      "My stillness cut you loose.",
      "The guilt is my own frost.",
      "I didn’t guard your glow.",
      "My choices lost your laugh.",
      "The sorrow is my own mark.",
      "I let the quiet fester.",
      "My ego sank your star.",
      "The regret is my own tide.",
      "I didn’t feel your fading.",
      "My fears broke your shore.",
      "The fault is my own echo.",
      "I crushed your gentle tide.",
      "My silence was your drift.",
      "The guilt is my own weight.",
      "I didn’t lift your spirit.",
      "My doubts dimmed your dawn.",
      "The blame is my own scar.",
      "I let your song fade out.",
      "My pride stole your breath.",
      "The remorse is my own frost.",
      "I didn’t hear your breaking.",
      "My fears sank your light.",
      "The fault is my own thread.",
      "I failed your fragile peace.",
      "My stillness lost your trust.",
      "The guilt is my own shroud.",
      "I didn’t keep you near.",
      "My choices hurt your soul.",
      "The sorrow is my own seed.",
      "I let the doubt consume.",
      "My ego tore your calm.",
      "The regret is my own chain.",
      "I didn’t see your shadow.",
      "My fears drowned your hope.",
      "The fault is my own fracture.",
      "I broke your quiet dawn.",
      "My silence was your fall.",
      "The guilt is my own storm.",
      "I didn’t hold your flame.",
      "My doubts buried your smile.",
      "The blame is my own tide.",
      "I let your glow slip free.",
      "My pride crushed your dreams.",
      "The remorse is my own weight.",
      "I didn’t catch your drift.",
      "My fears locked your heart.",
      "The fault is my own wound.",
      "I failed your tender spark.",
      "My stillness cut your thread.",
      "The guilt is my own frost.",
      "I didn’t guard your peace.",
      "My choices lost your light.",
      "The sorrow is my own mark.",
      "I let the dark take hold.",
      "My ego sank your tide.",
      "The regret is my own echo.",
      "I didn’t feel your loss.",
      "My fears broke your calm.",
      "The fault is my own scar.",
      "I crushed your fragile song.",
      "My silence was your void.",
      "The guilt is my own shroud.",
      "I didn’t lift your glow.",
      "My doubts drowned your star.",
      "The blame is my own chain.",
      "I let your hope slip free.",
      "My pride stole your dawn.",
      "The remorse is my own frost.",
      "I didn’t hear your drift.",
      "My fears sank your shore.",
      "The fault is my own thread.",
      "I failed your gentle light.",
      "My stillness lost your flame.",
      "The guilt is my own tide.",
      "I didn’t keep you safe.",
      "My choices hurt your glow.",
      "The sorrow is my own seed.",
      "I let the quiet grow.",
      "My ego tore your peace.",
      "The regret is my own weight.",
      "I didn’t see your fading.",
      "My fears broke your trust.",
      "The fault is my own fracture.",
      "I crushed your tender calm.",
      "My silence was your cage.",
      "I let you break me.",
      "You never even noticed.",
      "I was just an option, not a priority.",
      "The silence said more than you ever did.",
      "I cared too much. You didn't care at all.",
      "I kept waiting for something that never came.",
      "Some wounds never heal.",
      "If I mattered, you'd still be here.",
      "I should have been enough.",
      "You let me go so easily.",
      "I wish I could unmeet you.",
      "I still wait for a message that never comes.",
      "I wanted forever, you wanted convenience.",
      "We never even got closure.",
      "Maybe I was just a lesson, not a love.",
      "You promised, then you left.",
      "I should have listened when they warned me.",
      "I deserved more than unanswered texts.",
      "I was there for you. You were nowhere for me.",
      "You always said 'maybe later.' Later never came.",
      "Every goodbye leaves a scar.",
      "I still hear your silence.",
      "You were never truly mine.",
      "Regrets whisper in the dark.",
      "I lost parts of myself with you.",
      "Love turned cold too fast.",
      "Your absence echoes in my heart.",
      "I wished for more than what was given.",
      "I keep your ghost in every memory.",
      "Your shadow lingers in my dreams.",
      "I hoped for warmth, found only frost.",
      "Loneliness became my only friend.",
      "I carry the weight of unspoken words.",
      "Our memories haunt me daily.",
      "Every moment with you was bittersweet.",
      "I tried to hold on, but you slipped away.",
      "Silence became our final conversation.",
      "I wore my heart on a fragile sleeve.",
      "The truth hurts more than lies.",
      "I wish I could forget what we had.",
      "I drown in a sea of missed chances.",
      "I kept falling, even when I knew the end.",
      "You left behind more than empty promises.",
      "I once believed in us, now I only believe in solitude.",
      "I built dreams on promises that crumbled.",
      "The mirror reflects a stranger now.",
      "I still search for the love that vanished.",
      "Every memory is a bittersweet reminder.",
      "I stand alone in the ruins of our past.",
      "I sacrificed my soul for a love unreturned.",
      "The pain of goodbye never truly fades.",
      "I linger in the shadow of what could have been.",
      "Every heartbeat echoes your absence.",
      "I hoped you would be different.",
      "Your silence is louder than any words.",
      "I gave my all, but it wasn't enough.",
      "Every promise you broke still stings.",
      "I hide my scars behind a forced smile.",
      "I lost more than I ever thought possible.",
      "The emptiness inside speaks volumes.",
      "I watch the rain, feeling every drop of sorrow.",
      "I yearn for a past that can never return.",
      "I wear my solitude like a second skin.",
      "I fell for dreams that were never real.",
      "I mourn the future that we never had.",
      "Every tear tells a story of loss.",
      "I held on, even when I knew I should let go.",
      "The cold truth is harder to bear than the lies.",
      "I built hope on a foundation of despair.",
      "In the silence, my heart still whispers your name."
    ],
    []
  );
  
  const [currentIndex, setCurrentIndex] = useState(() => Math.floor(Math.random() * messages.length));
  const [displayText, setDisplayText] = useState("");
  const [isDeleting, setIsDeleting] = useState(false);
  const [isMistyped, setIsMistyped] = useState(false);
  const [charIndex, setCharIndex] = useState(0);

  useEffect(() => {
    const currentMessage = messages[currentIndex];
    let delay = Math.random() * 100 + 100; // Typing delay between 100-200ms
    if (isDeleting) {
      delay = 50; // Faster deletion
    }

    const timeout = setTimeout(() => {
      if (!isDeleting) {
        if (!isMistyped && Math.random() < 0.1 && charIndex > 0) {
          const wrongChar = String.fromCharCode(97 + Math.floor(Math.random() * 26));
          setDisplayText(currentMessage.substring(0, charIndex) + wrongChar);
          setIsMistyped(true);
        } else if (isMistyped) {
          setDisplayText(currentMessage.substring(0, charIndex));
          setIsMistyped(false);
        } else {
          const nextCharIndex = charIndex + 1;
          setDisplayText(currentMessage.substring(0, nextCharIndex));
          setCharIndex(nextCharIndex);
          if (nextCharIndex === currentMessage.length) {
            setTimeout(() => setIsDeleting(true), 2000);
          }
        }
      } else {
        if (charIndex > 0) {
          setDisplayText(currentMessage.substring(0, charIndex - 1));
          setCharIndex(charIndex - 1);
        } else {
          setIsDeleting(false);
          setCurrentIndex(Math.floor(Math.random() * messages.length));
        }
      }
    }, delay);

    return () => clearTimeout(timeout);
  }, [charIndex, isDeleting, isMistyped, currentIndex, messages]);

  return (
    <div className="typing-effect text-center text-lg font-mono text-[var(--text)] min-h-[3rem] transition-all duration-300">
      {displayText}
    </div>
  );
};

export default TypingEffect;
